WORLD = {'name': 'Basics', 'title': 'print, variables, arithmetic, functions'}

# A drill is one concept shown ten different ways. Each round is its own
# small task with its own brief, starter, expected output and hint.
DRILLS = [
    {'id': 's1-1',
     'title': 'Print and variables',
     'brief': 'Printing values, and printing what a variable holds.',
     'lesson': 'print() writes something to the screen. Put a value inside the brackets: text goes in quotes, '
               'numbers do not. A variable is a name for a value, made with =, and print(name) shows what it '
               'holds.  Example: greeting = "hey"  then  print(greeting)',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['print', 'variables'],
     'rounds': [{'brief': 'Print the word rocket.',
                 'starter': '',
                 'expected': 'rocket\n',
                 'hidden': '',
                 'hint': 'print("rocket")',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print the number 42.',
                 'starter': '',
                 'expected': '42\n',
                 'hidden': '',
                 'hint': 'print(42)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print what name holds.',
                 'starter': 'name = "Zoe"\n',
                 'expected': 'Zoe\n',
                 'hidden': '',
                 'hint': 'print(name)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print the two variables on one line, separated by a space.',
                 'starter': 'first = "hello"\nsecond = "moon"\n',
                 'expected': 'hello moon\n',
                 'hidden': '',
                 'hint': 'print(first, second)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print the year, then the month, each on its own line.',
                 'starter': 'year = 2026\nmonth = 9\n',
                 'expected': '2026\n9\n',
                 'hidden': '',
                 'hint': 'print(year)\nprint(month)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print the three words on one line separated by dashes, using sep.',
                 'starter': 'a = "up"\nb = "and"\nc = "away"\n',
                 'expected': 'up-and-away\n',
                 'hidden': '',
                 'hint': 'print(a, b, c, sep="-")',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print planet twice on one line with a space between.',
                 'starter': 'planet = "Mars"\n',
                 'expected': 'Mars Mars\n',
                 'hidden': '',
                 'hint': 'print(planet, planet)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Store the word comet in a variable called word, then print it.',
                 'starter': '# make the variable, then print it\n',
                 'expected': 'comet\n',
                 'hidden': '',
                 'hint': 'word = "comet"\nprint(word)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print an empty line, then the word done.',
                 'starter': '',
                 'expected': '\ndone\n',
                 'hidden': '',
                 'hint': 'print()\nprint("done")',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'},
                {'brief': 'Print speed, then change speed to 30 and print it again.',
                 'starter': 'speed = 10\n',
                 'expected': '10\n30\n',
                 'hidden': '',
                 'hint': 'print(speed)\nspeed = 30\nprint(speed)',
                 'tip': 'print(...) shows a value. Text needs quotes, a variable name does not.'}]},
    {'id': 's1-2',
     'title': 'Arithmetic',
     'brief': 'Adding, subtracting, multiplying, dividing, powers and remainders.',
     'lesson': 'Python does maths with the usual signs: + - * /. Two extra ones matter: // keeps only the whole '
               'part of a division, and % gives the remainder. ** raises to a power.  Example: 17 // 5 is 3, 17 '
               '% 5 is 2, 2 ** 3 is 8',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['arithmetic'],
     'rounds': [{'brief': 'Print the sum of a and b.',
                 'starter': 'a = 12\nb = 30\n',
                 'expected': '42\n',
                 'hidden': '',
                 'hint': 'print(a + b)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print b minus a.',
                 'starter': 'a = 12\nb = 30\n',
                 'expected': '18\n',
                 'hidden': '',
                 'hint': 'print(b - a)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print the product of width and height.',
                 'starter': 'width = 6\nheight = 9\n',
                 'expected': '54\n',
                 'hidden': '',
                 'hint': 'print(width * height)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print total divided by parts (a normal division).',
                 'starter': 'total = 90\nparts = 4\n',
                 'expected': '22.5\n',
                 'hidden': '',
                 'hint': 'print(total / parts)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print how many whole boxes of size fit in total, using floor division.',
                 'starter': 'total = 47\nsize = 6\n',
                 'expected': '7\n',
                 'hidden': '',
                 'hint': 'print(total // size)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print what is left over when total is split into boxes of size.',
                 'starter': 'total = 47\nsize = 6\n',
                 'expected': '5\n',
                 'hidden': '',
                 'hint': 'print(total % size)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print 2 to the power of n.',
                 'starter': 'n = 12\n',
                 'expected': '4096\n',
                 'hidden': '',
                 'hint': 'print(2 ** n)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print the average of the three numbers.',
                 'starter': 'a = 8\nb = 11\nc = 20\n',
                 'expected': '13.0\n',
                 'hidden': '',
                 'hint': 'print((a + b + c) / 3)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Add 5 to count using += and print count.',
                 'starter': 'count = 7\n',
                 'expected': '12\n',
                 'hidden': '',
                 'hint': 'count += 5\nprint(count)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'},
                {'brief': 'Print the price with 21 percent tax added.',
                 'starter': 'price = 200\n',
                 'expected': '242.0\n',
                 'hidden': '',
                 'hint': 'print(price * 1.21)',
                 'tip': '+ - * /, and // for the whole part, % for the remainder, ** for a power.'}]},
    {'id': 's1-3',
     'title': 'Numbers and rounding',
     'brief': 'Whole numbers, decimals, rounding and converting between them.',
     'lesson': 'Numbers come in two kinds: whole numbers like 7 and decimals like 7.5. round(x, 2) rounds to 2 '
               'decimals, int() and float() convert, and min, max and abs are built in.  Example: round(2.567, '
               '1) is 2.6',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['round', 'int', 'float'],
     'rounds': [{'brief': 'Print pi rounded to 2 decimals.',
                 'starter': 'pi = 3.14159265\n',
                 'expected': '3.14\n',
                 'hidden': '',
                 'hint': 'print(round(pi, 2))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the number rounded to the nearest whole number.',
                 'starter': 'number = 7.6\n',
                 'expected': '8\n',
                 'hidden': '',
                 'hint': 'print(round(number))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Turn the text into a number and add 1, then print it.',
                 'starter': 'text = "41"\n',
                 'expected': '42\n',
                 'hidden': '',
                 'hint': 'print(int(text) + 1)',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the type of value.',
                 'starter': 'value = 3.5\n',
                 'expected': "<class 'float'>\n",
                 'hidden': '',
                 'hint': 'print(type(value))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the whole-number part of value using int().',
                 'starter': 'value = 9.87\n',
                 'expected': '9\n',
                 'hidden': '',
                 'hint': 'print(int(value))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the absolute value of n.',
                 'starter': 'n = -14\n',
                 'expected': '14\n',
                 'hidden': '',
                 'hint': 'print(abs(n))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the smallest of the three numbers using min.',
                 'starter': 'a = 14\nb = 3\nc = 9\n',
                 'expected': '3\n',
                 'hidden': '',
                 'hint': 'print(min(a, b, c))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the largest number in the list using max.',
                 'starter': 'numbers = [4, 19, 7]\n',
                 'expected': '19\n',
                 'hidden': '',
                 'hint': 'print(max(numbers))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print the number as text joined with the word items, using str().',
                 'starter': 'count = 5\n',
                 'expected': '5 items\n',
                 'hidden': '',
                 'hint': 'print(str(count) + " items")',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'},
                {'brief': 'Print 1 divided by 3 rounded to 3 decimals.',
                 'starter': '',
                 'expected': '0.333\n',
                 'hidden': '',
                 'hint': 'print(round(1 / 3, 3))',
                 'tip': 'round(x, digits), int(x), float(x), abs(x), min(...), max(...).'}]},
    {'id': 's1-4',
     'title': 'Functions that return',
     'brief': 'Defining a function, returning a value, and calling it.',
     'lesson': 'A function is a small named recipe. def name(inputs): starts it, the body is indented, and '
               'return hands a value back to whoever called it. Calling it looks like name(3).  Example: def '
               'twice(x): return x * 2, then twice(4) is 8',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['functions', 'return'],
     'rounds': [{'brief': 'Write double(x) that returns x times two.',
                 'starter': '# define double here\n',
                 'expected': '42\n',
                 'hidden': 'print(double(21))\n',
                 'hint': 'def double(x):\n    return x * 2',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write add(a, b) that returns the sum.',
                 'starter': '# define add here\n',
                 'expected': '12\n',
                 'hidden': 'print(add(3, 9))\n',
                 'hint': 'def add(a, b):\n    return a + b',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write square(n) that returns n times n.',
                 'starter': '# define square here\n',
                 'expected': '49\n',
                 'hidden': 'print(square(7))\n',
                 'hint': 'def square(n):\n    return n * n',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write hello(name) that returns the word Hello, a space, and the name.',
                 'starter': '# define hello here\n',
                 'expected': 'Hello Ivy\n',
                 'hidden': 'print(hello("Ivy"))\n',
                 'hint': 'def hello(name):\n    return "Hello " + name',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write minutes(seconds) that returns the whole minutes in seconds.',
                 'starter': '# define minutes here\n',
                 'expected': '4\n',
                 'hidden': 'print(minutes(250))\n',
                 'hint': 'def minutes(seconds):\n    return seconds // 60',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write is_teen(age) that returns True when age is between 13 and 19.',
                 'starter': '# define is_teen here\n',
                 'expected': 'True\nFalse\n',
                 'hidden': 'print(is_teen(15))\nprint(is_teen(30))\n',
                 'hint': 'def is_teen(age):\n    return 13 <= age <= 19',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write average(a, b) that returns the mean of the two.',
                 'starter': '# define average here\n',
                 'expected': '5.5\n',
                 'hidden': 'print(average(4, 7))\n',
                 'hint': 'def average(a, b):\n    return (a + b) / 2',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write a function ten() with no parameters that returns 10, and print ten() plus '
                          'ten().',
                 'starter': '# define ten here, then print ten() + ten()\n',
                 'expected': '20\n',
                 'hidden': '',
                 'hint': 'def ten():\n    return 10\n\nprint(ten() + ten())',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write area(w, h) and use it to print the area of a 4 by 6 rectangle.',
                 'starter': '# define area here, then print area(4, 6)\n',
                 'expected': '24\n',
                 'hidden': '',
                 'hint': 'def area(w, h):\n    return w * h\n\nprint(area(4, 6))',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'},
                {'brief': 'Write cube(n) that returns n to the third power, and print cube(3).',
                 'starter': '# define cube here, then print cube(3)\n',
                 'expected': '27\n',
                 'hidden': '',
                 'hint': 'def cube(n):\n    return n ** 3\n\nprint(cube(3))',
                 'tip': 'def name(inputs): then an indented body, and return gives the value back.'}]},
    # add your own drills here
]
