WORLD = {'name': 'Functions', 'title': 'parameters and return, defaults, several values, functions as values, recursion'}

# A drill is one concept shown ten different ways. Each round is its own
# small task with its own brief, starter, expected output and hint.
DRILLS = [
    {'id': 's6-1',
     'title': 'Parameters and return',
     'brief': 'What a parameter is, why the name in def is the name you use inside, and what return does.',
     'lesson': 'A function is a recipe with a name. The names in the brackets after def are parameters: empty '
               'boxes that get filled when someone calls the function. Inside the function you use those names '
               'as if they were normal variables. return sends a value back to the caller, and the function '
               'stops right there. print only shows something on screen, it does not give anything back.  '
               'Example: def double(n): return n * 2, then double(4) is 8',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['functions', 'parameters', 'return'],
     'rounds': [{'brief': 'Write hello() with no parameters that returns the word hi.',
                 'starter': '# define hello here\n',
                 'expected': 'hi\n',
                 'hidden': 'print(hello())\n',
                 'hint': 'def hello():\n    return "hi"',
                 'tip': 'def hello(): starts the function; return hands a value back to whoever called it.'},
                {'brief': 'Write echo(word) that returns exactly what it was given.',
                 'starter': '# define echo here\n',
                 'expected': 'moon\n7\n',
                 'hidden': 'print(echo("moon"))\nprint(echo(7))\n',
                 'hint': 'def echo(word):\n    return word',
                 'tip': 'word is the parameter: a name for whatever value the caller passes in. Inside the '
                        'function you use that name.'},
                {'brief': 'Write double(n) that returns n times two.',
                 'starter': '# define double here\n',
                 'expected': '8\n20\n',
                 'hidden': 'print(double(4))\nprint(double(10))\n',
                 'hint': 'def double(n):\n    return n * 2',
                 'tip': 'the caller writes double(4); inside, n is 4. Use n in the calculation and return the '
                        'result.'},
                {'brief': 'Write add(a, b) that returns the sum of both parameters.',
                 'starter': '# define add here\n',
                 'expected': '5\n15\n',
                 'hidden': 'print(add(2, 3))\nprint(add(10, 5))\n',
                 'hint': 'def add(a, b):\n    return a + b',
                 'tip': 'two parameters, separated by a comma. They are filled in the order the caller gives '
                        'them.'},
                {'brief': 'Write shout(word) that RETURNS the word in upper case. Do not print inside the '
                          'function.',
                 'starter': '# define shout here\n',
                 'expected': 'HEY\n',
                 'hidden': 'print(shout("hey"))\n',
                 'hint': 'def shout(word):\n    return word.upper()',
                 'tip': 'print shows a value, return gives it back to the caller. The caller prints here, so '
                        'your function must return.'},
                {'brief': 'Write is_big(n) that returns True when n is above 100, otherwise False.',
                 'starter': '# define is_big here\n',
                 'expected': 'True\nFalse\n',
                 'hidden': 'print(is_big(500))\nprint(is_big(3))\n',
                 'hint': 'def is_big(n):\n    return n > 100',
                 'tip': 'a comparison like n > 100 already is True or False, so you can return it directly.'},
                {'brief': 'Write square(n) that returns n times n, then print square(4) plus square(3).',
                 'starter': '# define square here, then print square(4) + square(3)\n',
                 'expected': '25\n',
                 'hidden': '',
                 'hint': 'def square(n):\n    return n * n\n\nprint(square(4) + square(3))',
                 'tip': 'a returned value can be used right away: square(4) is 16 wherever you write it.'},
                {'brief': 'Write greet(name) that returns "hi " followed by the name.',
                 'starter': '# define greet here\n',
                 'expected': 'hi Bo\nhi Ivy\n',
                 'hidden': 'print(greet("Bo"))\nprint(greet("Ivy"))\n',
                 'hint': 'def greet(name):\n    return "hi " + name',
                 'tip': 'the same function works for any value: each call fills the parameter with a new name.'},
                {'brief': 'Write first_word(text) that returns only the first word of the text.',
                 'starter': '# define first_word here\n',
                 'expected': 'to\n',
                 'hidden': 'print(first_word("to the moon"))\n',
                 'hint': 'def first_word(text):\n    return text.split()[0]',
                 'tip': 'text.split() gives a list of words; [0] takes the first. return sends that one word '
                        'back.'},
                {'brief': 'Write sign(n) that returns "neg" for numbers below zero and "pos" otherwise.',
                 'starter': '# define sign here\n',
                 'expected': 'neg\npos\n',
                 'hidden': 'print(sign(-4))\nprint(sign(9))\n',
                 'hint': 'def sign(n):\n    if n < 0:\n        return "neg"\n    return "pos"',
                 'tip': 'return ends the function at once, so after the if you can simply return the other '
                        'answer.'}]},
    {'id': 's6-2',
     'title': 'Parameters and defaults',
     'brief': 'Positional, default and keyword arguments.',
     'lesson': 'Parameters are the names in the def line. A default like greeting="hi" is used when the caller '
               'leaves it out. Callers can name arguments: greet(name="Bo"). *nums collects any number of '
               'values, **options collects named ones.  Example: def greet(name, greeting="hi"):',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['functions', 'default arguments', 'keyword arguments'],
     'rounds': [{'brief': 'Write greet(name, greeting="hi") that returns greeting, a space, then the name.',
                 'starter': '# define greet here\n',
                 'expected': 'hi Sam\nyo Kim\n',
                 'hidden': 'print(greet("Sam"))\nprint(greet("Kim", "yo"))\n',
                 'hint': 'def greet(name, greeting="hi"):\n    return greeting + " " + name',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write power(base, exponent=2) that returns base to the exponent.',
                 'starter': '# define power here\n',
                 'expected': '25\n1024\n',
                 'hidden': 'print(power(5))\nprint(power(2, 10))\n',
                 'hint': 'def power(base, exponent=2):\n    return base ** exponent',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write repeat(word, times=3) that returns the word repeated that many times.',
                 'starter': '# define repeat here\n',
                 'expected': 'ababab\nxxxxx\n',
                 'hidden': 'print(repeat("ab"))\nprint(repeat("x", 5))\n',
                 'hint': 'def repeat(word, times=3):\n    return word * times',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write describe(name, age, city="unknown") returning: name, age, from city.',
                 'starter': '# define describe here\n',
                 'expected': 'Ada, 36, from London\nSam, 20, from unknown\n',
                 'hidden': 'print(describe("Ada", 36, city="London"))\nprint(describe(age=20, name="Sam"))\n',
                 'hint': 'def describe(name, age, city="unknown"):\n    return f"{name}, {age}, from {city}"',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write total(*numbers) that returns the sum of any number of arguments.',
                 'starter': '# define total here\n',
                 'expected': '6\n0\n',
                 'hidden': 'print(total(1, 2, 3))\nprint(total())\n',
                 'hint': 'def total(*numbers):\n    return sum(numbers)',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write show(**options) that prints each option as key=value, one per line.',
                 'starter': '# define show here\n',
                 'expected': 'a=1\nb=x\n',
                 'hidden': 'show(a=1, b="x")\n',
                 'hint': 'def show(**options):\n'
                         '    for key, value in options.items():\n'
                         '        print(f"{key}={value}")',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write add_item(item, items=None) that appends to a new list when none is given.',
                 'starter': '# define add_item here\n',
                 'expected': '[1]\n[2]\n[1, 2, 3]\n',
                 'hidden': 'print(add_item(1))\nprint(add_item(2))\nprint(add_item(3, [1, 2]))\n',
                 'hint': 'def add_item(item, items=None):\n'
                         '    if items is None:\n'
                         '        items = []\n'
                         '    items.append(item)\n'
                         '    return items',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write split_bill(total, people=2, tip=0) returning the rounded share per person, 2 '
                          'decimals.',
                 'starter': '# define split_bill here\n',
                 'expected': '25.0\n33.33\n27.5\n',
                 'hidden': 'print(split_bill(50))\n'
                           'print(split_bill(100, people=3))\n'
                           'print(split_bill(100, tip=10, people=4))\n',
                 'hint': 'def split_bill(total, people=2, tip=0):\n    return round((total + tip) / people, 2)',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write clamp(n, low=0, high=10) that returns n kept between low and high.',
                 'starter': '# define clamp here\n',
                 'expected': '10\n0\n3\n',
                 'hidden': 'print(clamp(15))\nprint(clamp(-4))\nprint(clamp(5, high=3))\n',
                 'hint': 'def clamp(n, low=0, high=10):\n'
                         '    if n < low:\n'
                         '        return low\n'
                         '    if n > high:\n'
                         '        return high\n'
                         '    return n',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'},
                {'brief': 'Write shout(text, mark="!") returning the text in upper case with the mark on the '
                          'end.',
                 'starter': '# define shout here\n',
                 'expected': 'HI!\nGO?\n',
                 'hidden': 'print(shout("hi"))\nprint(shout("go", "?"))\n',
                 'hint': 'def shout(text, mark="!"):\n    return text.upper() + mark',
                 'tip': 'def f(a, b=default): and call with f(1) or f(1, b=2).'}]},
    {'id': 's6-3',
     'title': 'Returning several things',
     'brief': 'Tuples, unpacking, and early returns.',
     'lesson': 'return a, b hands back two values as a tuple, and x, y = pair unpacks them. A return inside a '
               'loop ends the function right there.  Example: lo, hi = min_max(nums)',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['tuples', 'return', 'unpacking'],
     'rounds': [{'brief': 'Write min_max(numbers) that returns the smallest and the largest as a tuple.',
                 'starter': '# define min_max here\n',
                 'expected': '(1, 9)\n',
                 'hidden': 'print(min_max([4, 9, 1]))\n',
                 'hint': 'def min_max(numbers):\n    return min(numbers), max(numbers)',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write divmod_by(n, k) that returns the whole quotient and the remainder.',
                 'starter': '# define divmod_by here\n',
                 'expected': '(3, 2)\n',
                 'hidden': 'print(divmod_by(17, 5))\n',
                 'hint': 'def divmod_by(n, k):\n    return n // k, n % k',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Unpack the tuple into x and y and print x plus y.',
                 'starter': 'point = (3, 4)\n',
                 'expected': '7\n',
                 'hidden': '',
                 'hint': 'x, y = point\nprint(x + y)',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write first_last(items) returning the first and last item.',
                 'starter': '# define first_last here\n',
                 'expected': "('a', 'c')\n",
                 'hidden': 'print(first_last(["a", "b", "c"]))\n',
                 'hint': 'def first_last(items):\n    return items[0], items[-1]',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Call min_max and unpack the result into lo and hi, then print hi minus lo.',
                 'starter': 'def min_max(numbers):\n'
                            '    return min(numbers), max(numbers)\n'
                            '\n'
                            'numbers = [4, 9, 1]\n',
                 'expected': '8\n',
                 'hidden': '',
                 'hint': 'lo, hi = min_max(numbers)\nprint(hi - lo)',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write stats(numbers) returning the count, the total and the mean as a tuple.',
                 'starter': '# define stats here\n',
                 'expected': '(3, 12, 4.0)\n',
                 'hidden': 'print(stats([2, 4, 6]))\n',
                 'hint': 'def stats(numbers):\n'
                         '    return len(numbers), sum(numbers), sum(numbers) / len(numbers)',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write find(items, target) returning the index of target, or -1 if missing, using an '
                          'early return.',
                 'starter': '# define find here\n',
                 'expected': '2\n-1\n',
                 'hidden': 'print(find(["a", "b", "c"], "c"))\nprint(find(["a"], "z"))\n',
                 'hint': 'def find(items, target):\n'
                         '    for i, item in enumerate(items):\n'
                         '        if item == target:\n'
                         '            return i\n'
                         '    return -1',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Swap the values of a and b using tuple unpacking and print a then b.',
                 'starter': 'a = 1\nb = 2\n',
                 'expected': '2\n1\n',
                 'hidden': '',
                 'hint': 'a, b = b, a\nprint(a)\nprint(b)',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write name_parts(full) returning the first and last name from a full name.',
                 'starter': '# define name_parts here\n',
                 'expected': "('Grace', 'Hopper')\n",
                 'hidden': 'print(name_parts("Grace Hopper"))\n',
                 'hint': 'def name_parts(full):\n    first, last = full.split()\n    return first, last',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'},
                {'brief': 'Write safe_first(items) returning the first item, or None for an empty list.',
                 'starter': '# define safe_first here\n',
                 'expected': '7\nNone\n',
                 'hidden': 'print(safe_first([7, 8]))\nprint(safe_first([]))\n',
                 'hint': 'def safe_first(items):\n'
                         '    if len(items) == 0:\n'
                         '        return None\n'
                         '    return items[0]',
                 'tip': 'return a, b gives a tuple; x, y = ... unpacks it.'}]},
    {'id': 's6-4',
     'title': 'Functions as values',
     'brief': 'Passing functions around, sorted with key, map and lambda.',
     'lesson': 'A function is a value: you can store it, pass it to another function, or make one on the spot '
               'with lambda. sorted(items, key=len) sorts by what key returns.  Example: sorted(words, '
               'key=lambda w: w[-1])',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['functions as values', 'sorted', 'lambda'],
     'rounds': [{'brief': 'Print the words sorted from shortest to longest.',
                 'starter': 'words = ["kiwi", "fig", "banana"]\n',
                 'expected': "['fig', 'kiwi', 'banana']\n",
                 'hidden': '',
                 'hint': 'print(sorted(words, key=len))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Write apply(func, value) that returns func(value).',
                 'starter': '# define apply here\n',
                 'expected': '4\n7\n',
                 'hidden': 'print(apply(len, "moon"))\nprint(apply(abs, -7))\n',
                 'hint': 'def apply(func, value):\n    return func(value)',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Write twice(func, value) that applies func two times.',
                 'starter': '# define twice here\n',
                 'expected': '7\n',
                 'hidden': 'def add3(x):\n    return x + 3\n\nprint(twice(add3, 1))\n',
                 'hint': 'def twice(func, value):\n    return func(func(value))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Print the list of lengths using map and len.',
                 'starter': 'words = ["a", "bb", "ccc"]\n',
                 'expected': '[1, 2, 3]\n',
                 'hidden': '',
                 'hint': 'print(list(map(len, words)))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Print the users sorted by age, youngest first (as a list of dicts).',
                 'starter': 'users = [{"name": "A", "age": 40}, {"name": "B", "age": 20}]\n',
                 'expected': "[{'name': 'B', 'age': 20}, {'name': 'A', 'age': 40}]\n",
                 'hidden': '',
                 'hint': 'print(sorted(users, key=lambda u: u["age"]))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': "Print the oldest user's name using max with a key.",
                 'starter': 'users = [{"name": "A", "age": 40}, {"name": "B", "age": 20}]\n',
                 'expected': 'A\n',
                 'hidden': '',
                 'hint': 'print(max(users, key=lambda u: u["age"])["name"])',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Store the function len in a variable called measure and print measure applied to the '
                          'word.',
                 'starter': 'word = "galaxy"\n',
                 'expected': '6\n',
                 'hidden': '',
                 'hint': 'measure = len\nprint(measure(word))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Write make_adder(n) that returns a function which adds n to its argument.',
                 'starter': '# define make_adder here\n',
                 'expected': '15\n',
                 'hidden': 'add5 = make_adder(5)\nprint(add5(10))\n',
                 'hint': 'def make_adder(n):\n    def add(x):\n        return x + n\n    return add',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Print the numbers sorted from biggest to smallest using sorted with reverse.',
                 'starter': 'numbers = [3, 9, 1]\n',
                 'expected': '[9, 3, 1]\n',
                 'hidden': '',
                 'hint': 'print(sorted(numbers, reverse=True))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'},
                {'brief': 'Print the words sorted by their last letter.',
                 'starter': 'words = ["moon", "star", "sky"]\n',
                 'expected': "['moon', 'star', 'sky']\n",
                 'hidden': '',
                 'hint': 'print(sorted(words, key=lambda w: w[-1]))',
                 'tip': 'functions are values: pass them, store them, or use lambda x: ... inline.'}]},
    {'id': 's6-5',
     'title': 'Recursion',
     'brief': 'A function that calls itself with a smaller problem, and a base case first.',
     'lesson': 'A recursive function calls itself with a smaller problem. Always write the base case first, the '
               'smallest input that needs no more calls, and return it.  Example: if n == 0: return 1, then '
               'return n * factorial(n - 1)',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['recursion'],
     'rounds': [{'brief': 'Write factorial(n) using recursion. factorial(0) is 1.',
                 'starter': '# define factorial here\n',
                 'expected': '120\n',
                 'hidden': 'print(factorial(5))\n',
                 'hint': 'def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write sum_to(n) that returns 1 + 2 + ... + n using recursion.',
                 'starter': '# define sum_to here\n',
                 'expected': '55\n',
                 'hidden': 'print(sum_to(10))\n',
                 'hint': 'def sum_to(n):\n    if n == 0:\n        return 0\n    return n + sum_to(n - 1)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write power(base, exponent) using recursion, without **.',
                 'starter': '# define power here\n',
                 'expected': '256\n',
                 'hidden': 'print(power(2, 8))\n',
                 'hint': 'def power(base, exponent):\n'
                         '    if exponent == 0:\n'
                         '        return 1\n'
                         '    return base * power(base, exponent - 1)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write sum_digits(n) returning the sum of the digits, using recursion.',
                 'starter': '# define sum_digits here\n',
                 'expected': '10\n',
                 'hidden': 'print(sum_digits(1234))\n',
                 'hint': 'def sum_digits(n):\n'
                         '    if n < 10:\n'
                         '        return n\n'
                         '    return n % 10 + sum_digits(n // 10)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write fib(n) returning the n-th Fibonacci number: fib(0) is 0, fib(1) is 1.',
                 'starter': '# define fib here\n',
                 'expected': '55\n',
                 'hidden': 'print(fib(10))\n',
                 'hint': 'def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write count_down(n) that prints n, then n-1, down to 1, using recursion.',
                 'starter': '# define count_down here\n',
                 'expected': '3\n2\n1\n',
                 'hidden': 'count_down(3)\n',
                 'hint': 'def count_down(n):\n'
                         '    if n == 0:\n'
                         '        return\n'
                         '    print(n)\n'
                         '    count_down(n - 1)',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write reverse(text) that returns the text reversed using recursion.',
                 'starter': '# define reverse here\n',
                 'expected': 'tekcor\n',
                 'hidden': 'print(reverse("rocket"))\n',
                 'hint': 'def reverse(text):\n'
                         '    if len(text) <= 1:\n'
                         '        return text\n'
                         '    return reverse(text[1:]) + text[0]',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write total(numbers) that sums a list using recursion: first item plus the total of '
                          'the rest.',
                 'starter': '# define total here\n',
                 'expected': '10\n',
                 'hidden': 'print(total([1, 2, 3, 4]))\n',
                 'hint': 'def total(numbers):\n'
                         '    if len(numbers) == 0:\n'
                         '        return 0\n'
                         '    return numbers[0] + total(numbers[1:])',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write is_palindrome(text) using recursion: compare the ends, then check the inside.',
                 'starter': '# define is_palindrome here\n',
                 'expected': 'True\nFalse\n',
                 'hidden': 'print(is_palindrome("level"))\nprint(is_palindrome("rocket"))\n',
                 'hint': 'def is_palindrome(text):\n'
                         '    if len(text) <= 1:\n'
                         '        return True\n'
                         '    if text[0] != text[-1]:\n'
                         '        return False\n'
                         '    return is_palindrome(text[1:-1])',
                 'tip': 'base case first, then return something using the function on a smaller input.'},
                {'brief': 'Write flatten(items) that turns nested lists into one flat list using recursion.',
                 'starter': '# define flatten here\n',
                 'expected': '[1, 2, 3, 4, 5]\n',
                 'hidden': 'print(flatten([1, [2, [3, 4]], 5]))\n',
                 'hint': 'def flatten(items):\n'
                         '    result = []\n'
                         '    for item in items:\n'
                         '        if isinstance(item, list):\n'
                         '            result = result + flatten(item)\n'
                         '        else:\n'
                         '            result.append(item)\n'
                         '    return result',
                 'tip': 'base case first, then return something using the function on a smaller input.'}]},
    # add your own drills here
]
