WORLD = {'name': 'Strings', 'title': 'methods, slicing, f-strings, split and join'}

# A drill is one concept shown ten different ways. Each round is its own
# small task with its own brief, starter, expected output and hint.
DRILLS = [
    {'id': 's3-1',
     'title': 'String methods',
     'brief': 'upper, lower, strip, replace, startswith and friends.',
     'lesson': 'Text is a string. Strings have methods you call with a dot: .upper(), .lower(), .strip() removes '
               'spaces around, .replace(old, new) swaps text. They give a new string back.  Example: '
               '"hey".upper() is "HEY"',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['strings', 'methods'],
     'rounds': [{'brief': 'Print the word in upper case.',
                 'starter': 'word = "nebula"\n',
                 'expected': 'NEBULA\n',
                 'hidden': '',
                 'hint': 'print(word.upper())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the word in lower case.',
                 'starter': 'word = "GALAXY"\n',
                 'expected': 'galaxy\n',
                 'hidden': '',
                 'hint': 'print(word.lower())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the text without the spaces around it.',
                 'starter': 'text = "   orbit   "\n',
                 'expected': 'orbit\n',
                 'hidden': '',
                 'hint': 'print(text.strip())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the sentence with every cat replaced by dog.',
                 'starter': 'sentence = "the cat sat on the cat mat"\n',
                 'expected': 'the dog sat on the dog mat\n',
                 'hidden': '',
                 'hint': 'print(sentence.replace("cat", "dog"))',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print whether the file name ends with .py.',
                 'starter': 'name = "main.py"\n',
                 'expected': 'True\n',
                 'hidden': '',
                 'hint': 'print(name.endswith(".py"))',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print whether the word starts with a capital letter, using startswith and upper on '
                          'the first letter... or simply print word[0].isupper().',
                 'starter': 'word = "Saturn"\n',
                 'expected': 'True\n',
                 'hidden': '',
                 'hint': 'print(word[0].isupper())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the title with the first letter of every word in capitals.',
                 'starter': 'title = "the red planet"\n',
                 'expected': 'The Red Planet\n',
                 'hidden': '',
                 'hint': 'print(title.title())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the word with its first letter capitalised and the rest lower.',
                 'starter': 'word = "mARS"\n',
                 'expected': 'Mars\n',
                 'hidden': '',
                 'hint': 'print(word.capitalize())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print whether the text is made of digits only.',
                 'starter': 'text = "2026"\n',
                 'expected': 'True\n',
                 'hidden': '',
                 'hint': 'print(text.isdigit())',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'},
                {'brief': 'Print the position where sun first appears in the sentence, using find.',
                 'starter': 'sentence = "here comes the sun"\n',
                 'expected': '15\n',
                 'hidden': '',
                 'hint': 'print(sentence.find("sun"))',
                 'tip': 'call methods with a dot: text.upper(), text.strip(), text.replace(a, b).'}]},
    {'id': 's3-2',
     'title': 'Length, index and slice',
     'brief': 'len, indexing from the front and the back, and slicing.',
     'lesson': 'len(text) counts characters. text[0] is the first one, text[-1] the last. A slice text[a:b] '
               'takes from position a up to but not including b; leave a side empty to mean the start or the '
               'end.  Example: "python"[0:2] is "py"',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['len', 'indexing', 'slicing'],
     'rounds': [{'brief': 'Print how many characters the word has.',
                 'starter': 'word = "constellation"\n',
                 'expected': '13\n',
                 'hidden': '',
                 'hint': 'print(len(word))',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the first letter of the word.',
                 'starter': 'word = "quasar"\n',
                 'expected': 'q\n',
                 'hidden': '',
                 'hint': 'print(word[0])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the last letter of the word.',
                 'starter': 'word = "quasar"\n',
                 'expected': 'r\n',
                 'hidden': '',
                 'hint': 'print(word[-1])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the first three letters.',
                 'starter': 'word = "asteroid"\n',
                 'expected': 'ast\n',
                 'hidden': '',
                 'hint': 'print(word[:3])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print everything from the fourth character on.',
                 'starter': 'word = "asteroid"\n',
                 'expected': 'eroid\n',
                 'hidden': '',
                 'hint': 'print(word[3:])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the last two letters.',
                 'starter': 'word = "meteor"\n',
                 'expected': 'or\n',
                 'hidden': '',
                 'hint': 'print(word[-2:])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the word reversed, using a slice with step -1.',
                 'starter': 'word = "rotor"\n',
                 'expected': 'rotor\n',
                 'hidden': '',
                 'hint': 'print(word[::-1])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print every second letter, starting from the first.',
                 'starter': 'word = "abcdefgh"\n',
                 'expected': 'aceg\n',
                 'hidden': '',
                 'hint': 'print(word[::2])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the middle letter of the word (it has an odd length).',
                 'starter': 'word = "orbit"\n',
                 'expected': 'b\n',
                 'hidden': '',
                 'hint': 'print(word[len(word) // 2])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'},
                {'brief': 'Print the characters from index 2 up to but not including index 5.',
                 'starter': 'word = "spacecraft"\n',
                 'expected': 'ace\n',
                 'hidden': '',
                 'hint': 'print(word[2:5])',
                 'tip': 'len(text), text[0], text[-1], text[start:stop].'}]},
    {'id': 's3-3',
     'title': 'F-strings',
     'brief': 'Putting values inside text, then formatting them.',
     'lesson': 'An f-string is text with an f in front where anything inside {curly braces} is calculated and '
               'put in. After a colon inside the braces you can add a format code.  Example: f"{name} is {age}"',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['f-strings', 'formatting'],
     'rounds': [{'brief': 'Print: Hi NAME, using an f-string with the variable inside curly braces.',
                 'starter': 'name = "Noor"\n',
                 'expected': 'Hi Noor\n',
                 'hidden': '',
                 'hint': 'print(f"Hi {name}")',
                 'tip': 'an f-string starts with f before the quote: f"Hi {name}" puts the value of name in '
                        'place of {name}.'},
                {'brief': 'Print: NAME is AGE years old.',
                 'starter': 'name = "Bo"\nage = 31\n',
                 'expected': 'Bo is 31 years old.\n',
                 'hidden': '',
                 'hint': 'print(f"{name} is {age} years old.")',
                 'tip': 'you can put more than one {variable} in the same f-string; numbers need no str().'},
                {'brief': 'Print: 3 + 4 = 7, working the sum out inside the f-string.',
                 'starter': 'a = 3\nb = 4\n',
                 'expected': '3 + 4 = 7\n',
                 'hidden': '',
                 'hint': 'print(f"{a} + {b} = {a + b}")',
                 'tip': 'anything inside the braces is calculated first: {a + b} becomes 7.'},
                {'brief': 'Print: HELLO, NAME! with the name in upper case, done inside the braces.',
                 'starter': 'name = "Ada"\n',
                 'expected': 'HELLO, ADA!\n',
                 'hidden': '',
                 'hint': 'print(f"HELLO, {name.upper()}!")',
                 'tip': 'you can call a method inside the braces: {name.upper()}.'},
                {'brief': 'Print two lines with an f-string each: name: Omar and then length: 4.',
                 'starter': 'name = "Omar"\n',
                 'expected': 'name: Omar\nlength: 4\n',
                 'hidden': '',
                 'hint': 'print(f"name: {name}")\nprint(f"length: {len(name)}")',
                 'tip': 'len(name) inside the braces gives the number of letters.'},
                {'brief': 'Print the price with exactly 2 decimals, like 4.50.',
                 'starter': 'price = 4.5\n',
                 'expected': '4.50\n',
                 'hidden': '',
                 'hint': 'print(f"{price:.2f}")',
                 'tip': 'a colon inside the braces starts a format code: {price:.2f} means 2 digits after the '
                        'dot (f is for a decimal number).'},
                {'brief': 'Print the big number with a comma every three digits, like 9,876,543.',
                 'starter': 'n = 9876543\n',
                 'expected': '9,876,543\n',
                 'hidden': '',
                 'hint': 'print(f"{n:,}")',
                 'tip': 'the format code , adds thousands separators: {n:,}.'},
                {'brief': 'Print the ratio as a percentage with no decimals, like 75%.',
                 'starter': 'ratio = 0.75\n',
                 'expected': '75%\n',
                 'hidden': '',
                 'hint': 'print(f"{ratio:.0%}")',
                 'tip': 'the format code % multiplies by 100 and adds the sign; .0 means no decimals: '
                        '{ratio:.0%}.'},
                {'brief': 'Print the number padded with zeros to 3 digits, like 007.',
                 'starter': 'n = 7\n',
                 'expected': '007\n',
                 'hidden': '',
                 'hint': 'print(f"{n:03}")',
                 'tip': '{n:03} means: at least 3 characters wide, filled with zeros on the left.'},
                {'brief': 'Print the word right-aligned in a field 10 wide, between two bars, like |      moon|.',
                 'starter': 'word = "moon"\n',
                 'expected': '|      moon|\n',
                 'hidden': '',
                 'hint': 'print(f"|{word:>10}|")',
                 'tip': '{word:>10} means: make it 10 wide and push the text to the right; < pushes left, ^ '
                        'centres.'}]},
    {'id': 's3-4',
     'title': 'Split, join, count, in',
     'brief': 'Taking text apart and putting it together.',
     'lesson': '.split() cuts text into a list of words, "-".join(list) glues a list back together with a '
               'separator, .count(x) counts, and  x in text  asks whether text contains x.  Example: "a '
               'b".split() is ["a", "b"]',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['split', 'join', 'count', 'in'],
     'rounds': [{'brief': 'Print the list of words in the sentence.',
                 'starter': 'sentence = "to the stars"\n',
                 'expected': "['to', 'the', 'stars']\n",
                 'hidden': '',
                 'hint': 'print(sentence.split())',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print how many words the sentence has.',
                 'starter': 'sentence = "one small step for a person"\n',
                 'expected': '6\n',
                 'hidden': '',
                 'hint': 'print(len(sentence.split()))',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the words joined with a comma and a space.',
                 'starter': 'words = ["red", "green", "blue"]\n',
                 'expected': 'red, green, blue\n',
                 'hidden': '',
                 'hint': 'print(", ".join(words))',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print how many times the letter a appears in the word.',
                 'starter': 'word = "banana"\n',
                 'expected': '3\n',
                 'hidden': '',
                 'hint': 'print(word.count("a"))',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print whether the word moon is in the sentence.',
                 'starter': 'sentence = "fly me to the moon"\n',
                 'expected': 'True\n',
                 'hidden': '',
                 'hint': 'print("moon" in sentence)',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the username part of the email (before the @).',
                 'starter': 'email = "lena@example.com"\n',
                 'expected': 'lena\n',
                 'hidden': '',
                 'hint': 'print(email.split("@")[0])',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the domain part of the email (after the @).',
                 'starter': 'email = "lena@example.com"\n',
                 'expected': 'example.com\n',
                 'hidden': '',
                 'hint': 'print(email.split("@")[1])',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the words of the sentence one per line.',
                 'starter': 'sentence = "we choose the moon"\n',
                 'expected': 'we\nchoose\nthe\nmoon\n',
                 'hidden': '',
                 'hint': 'for word in sentence.split():\n    print(word)',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the letters of the word joined with dashes.',
                 'starter': 'word = "star"\n',
                 'expected': 's-t-a-r\n',
                 'hidden': '',
                 'hint': 'print("-".join(word))',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'},
                {'brief': 'Print the parts of the date (year, month, day) as a list, splitting on the dash.',
                 'starter': 'date = "2026-09-09"\n',
                 'expected': "['2026', '09', '09']\n",
                 'hidden': '',
                 'hint': 'print(date.split("-"))',
                 'tip': 'text.split(), "-".join(list), text.count(x), x in text.'}]},
    # add your own drills here
]
