WORLD = {'name': 'Comprehensions', 'title': 'list, filtered, dict and set forms, generators'}

# A drill is one concept shown ten different ways. Each round is its own
# small task with its own brief, starter, expected output and hint.
DRILLS = [
    {'id': 's7-1',
     'title': 'List comprehensions',
     'brief': 'Building a list in one expression.',
     'lesson': 'A list comprehension builds a list in one line: [expression for item in items]. Read it as: for '
               'each item, put the expression in.  Example: [n * 2 for n in numbers]',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['comprehensions'],
     'rounds': [{'brief': 'Print the squares of 1 to 5 as a list, with a comprehension.',
                 'starter': '',
                 'expected': '[1, 4, 9, 16, 25]\n',
                 'hidden': '',
                 'hint': 'print([n * n for n in range(1, 6)])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the list of each number doubled.',
                 'starter': 'numbers = [1, 2, 3]\n',
                 'expected': '[2, 4, 6]\n',
                 'hidden': '',
                 'hint': 'print([n * 2 for n in numbers])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the list of the words in upper case.',
                 'starter': 'words = ["go", "up"]\n',
                 'expected': "['GO', 'UP']\n",
                 'hidden': '',
                 'hint': 'print([w.upper() for w in words])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the list of lengths of the words.',
                 'starter': 'words = ["sun", "planet"]\n',
                 'expected': '[3, 6]\n',
                 'hidden': '',
                 'hint': 'print([len(w) for w in words])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the list of the first letters of the names.',
                 'starter': 'names = ["Ada", "Bo", "Cy"]\n',
                 'expected': "['A', 'B', 'C']\n",
                 'hidden': '',
                 'hint': 'print([name[0] for name in names])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the numbers from 0 to 9 as a list, using range in a comprehension.',
                 'starter': '',
                 'expected': '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n',
                 'hidden': '',
                 'hint': 'print([n for n in range(10)])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Write halves(numbers) returning a list with each number divided by two.',
                 'starter': '# define halves here\n',
                 'expected': '[1.0, 2.5, 4.0]\n',
                 'hidden': 'print(halves([2, 5, 8]))\n',
                 'hint': 'def halves(numbers):\n    return [n / 2 for n in numbers]',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print a list of the strings with the word km added to each number.',
                 'starter': 'distances = [3, 10]\n',
                 'expected': "['3 km', '10 km']\n",
                 'hidden': '',
                 'hint': 'print([f"{d} km" for d in distances])',
                 'tip': '[expression for item in items]'},
                {'brief': "Print the list of the users' names from the list of dicts.",
                 'starter': 'users = [{"name": "A"}, {"name": "B"}]\n',
                 'expected': "['A', 'B']\n",
                 'hidden': '',
                 'hint': 'print([u["name"] for u in users])',
                 'tip': '[expression for item in items]'},
                {'brief': 'Print the list of numbers 1 to 5 as text, using str in a comprehension.',
                 'starter': '',
                 'expected': "['1', '2', '3', '4', '5']\n",
                 'hidden': '',
                 'hint': 'print([str(n) for n in range(1, 6)])',
                 'tip': '[expression for item in items]'}]},
    {'id': 's7-2',
     'title': 'Filtering comprehensions',
     'brief': 'A comprehension with an if.',
     'lesson': 'Add an if at the end to keep only some items: [item for item in items if condition].  Example: '
               '[n for n in numbers if n > 10]',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['comprehensions', 'if'],
     'rounds': [{'brief': 'Print the list of only the even numbers.',
                 'starter': 'numbers = [1, 2, 3, 4, 5, 6]\n',
                 'expected': '[2, 4, 6]\n',
                 'hidden': '',
                 'hint': 'print([n for n in numbers if n % 2 == 0])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the list of numbers above 10.',
                 'starter': 'numbers = [4, 15, 9, 22]\n',
                 'expected': '[15, 22]\n',
                 'hidden': '',
                 'hint': 'print([n for n in numbers if n > 10])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the list of words longer than 3 letters.',
                 'starter': 'words = ["sun", "planet", "sky", "galaxy"]\n',
                 'expected': "['planet', 'galaxy']\n",
                 'hidden': '',
                 'hint': 'print([w for w in words if len(w) > 3])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the list of words that start with s.',
                 'starter': 'words = ["sun", "moon", "star"]\n',
                 'expected': "['sun', 'star']\n",
                 'hidden': '',
                 'hint': 'print([w for w in words if w.startswith("s")])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Write positives(numbers) returning only the numbers above zero.',
                 'starter': '# define positives here\n',
                 'expected': '[5, 8]\n',
                 'hidden': 'print(positives([-2, 5, -1, 8]))\n',
                 'hint': 'def positives(numbers):\n    return [n for n in numbers if n > 0]',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the squares of the odd numbers from 1 to 9.',
                 'starter': '',
                 'expected': '[1, 9, 25, 49, 81]\n',
                 'hidden': '',
                 'hint': 'print([n * n for n in range(1, 10) if n % 2 == 1])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the names of users older than 30.',
                 'starter': 'users = [{"name": "A", "age": 40}, {"name": "B", "age": 20}]\n',
                 'expected': "['A']\n",
                 'hidden': '',
                 'hint': 'print([u["name"] for u in users if u["age"] > 30])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Write short(names) returning the names of 3 letters or fewer, in lower case.',
                 'starter': '# define short here\n',
                 'expected': "['bo', 'kim']\n",
                 'hidden': 'print(short(["Bo", "Alexander", "Kim"]))\n',
                 'hint': 'def short(names):\n    return [name.lower() for name in names if len(name) <= 3]',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print the list of non-empty strings.',
                 'starter': 'items = ["a", "", "b", ""]\n',
                 'expected': "['a', 'b']\n",
                 'hidden': '',
                 'hint': 'print([s for s in items if s != ""])',
                 'tip': '[item for item in items if condition]'},
                {'brief': 'Print a list of the numbers divisible by 3 between 1 and 20.',
                 'starter': '',
                 'expected': '[3, 6, 9, 12, 15, 18]\n',
                 'hidden': '',
                 'hint': 'print([n for n in range(1, 21) if n % 3 == 0])',
                 'tip': '[item for item in items if condition]'}]},
    {'id': 's7-3',
     'title': 'Dict and set comprehensions',
     'brief': 'The same idea with curly braces.',
     'lesson': 'With curly braces you build a dict {key: value for ...} or a set {value for ...}. Sets have no '
               'order, so sort them when printing.  Example: {w: len(w) for w in words}',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['dict comprehension', 'set comprehension'],
     'rounds': [{'brief': 'Print a dict from each word to its length.',
                 'starter': 'words = ["hi", "hello"]\n',
                 'expected': "{'hi': 2, 'hello': 5}\n",
                 'hidden': '',
                 'hint': 'print({w: len(w) for w in words})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print a dict from each number 1 to 3 to its square.',
                 'starter': '',
                 'expected': '{1: 1, 2: 4, 3: 9}\n',
                 'hidden': '',
                 'hint': 'print({n: n * n for n in range(1, 4)})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Write lengths(words) returning a dict from word to length.',
                 'starter': '# define lengths here\n',
                 'expected': "{'a': 1, 'bcd': 3}\n",
                 'hidden': 'print(lengths(["a", "bcd"]))\n',
                 'hint': 'def lengths(words):\n    return {w: len(w) for w in words}',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print the sorted list of the different first letters of the words, using a set '
                          'comprehension.',
                 'starter': 'words = ["the", "quick", "tall"]\n',
                 'expected': "['q', 't']\n",
                 'hidden': '',
                 'hint': 'print(sorted({w[0] for w in words}))',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print a dict from each name to its upper case version.',
                 'starter': 'names = ["ada", "bo"]\n',
                 'expected': "{'ada': 'ADA', 'bo': 'BO'}\n",
                 'hidden': '',
                 'hint': 'print({name: name.upper() for name in names})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print the dict with the keys and values swapped.',
                 'starter': 'codes = {"a": 1, "b": 2}\n',
                 'expected': "{1: 'a', 2: 'b'}\n",
                 'hidden': '',
                 'hint': 'print({value: key for key, value in codes.items()})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print a dict of only the entries whose value is above 2.',
                 'starter': 'stock = {"a": 1, "b": 3, "c": 5}\n',
                 'expected': "{'b': 3, 'c': 5}\n",
                 'hidden': '',
                 'hint': 'print({k: v for k, v in stock.items() if v > 2})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Print the sorted set of word lengths.',
                 'starter': 'words = ["a", "bb", "cc", "ddd"]\n',
                 'expected': '[1, 2, 3]\n',
                 'hidden': '',
                 'hint': 'print(sorted({len(w) for w in words}))',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': 'Write squares(n) returning a dict from each number 1 to n to its square.',
                 'starter': '# define squares here\n',
                 'expected': '{1: 1, 2: 4, 3: 9, 4: 16}\n',
                 'hidden': 'print(squares(4))\n',
                 'hint': 'def squares(n):\n    return {k: k * k for k in range(1, n + 1)}',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'},
                {'brief': "Print a dict from each user's name to their age.",
                 'starter': 'users = [{"name": "A", "age": 40}, {"name": "B", "age": 20}]\n',
                 'expected': "{'A': 40, 'B': 20}\n",
                 'hidden': '',
                 'hint': 'print({u["name"]: u["age"] for u in users})',
                 'tip': '{key: value for ...} makes a dict, {value for ...} makes a set.'}]},
    {'id': 's7-4',
     'title': 'Generators with any, all, sum, max',
     'brief': 'A comprehension without brackets, fed straight into a function.',
     'lesson': 'Without brackets, a comprehension becomes a generator you feed straight into sum, any, all, min '
               'or max.  Example: sum(n * n for n in numbers)',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['generator', 'any', 'all', 'sum', 'max'],
     'rounds': [{'brief': 'Print the sum of the squares of 1 to 5 using a generator inside sum().',
                 'starter': '',
                 'expected': '55\n',
                 'hidden': '',
                 'hint': 'print(sum(n * n for n in range(1, 6)))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print whether any number is negative, using any().',
                 'starter': 'numbers = [3, -1, 7]\n',
                 'expected': 'True\n',
                 'hidden': '',
                 'hint': 'print(any(n < 0 for n in numbers))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print whether all numbers are positive, using all().',
                 'starter': 'numbers = [3, -1, 7]\n',
                 'expected': 'False\n',
                 'hidden': '',
                 'hint': 'print(all(n > 0 for n in numbers))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print the longest word using max with key=len.',
                 'starter': 'words = ["sun", "planet", "sky"]\n',
                 'expected': 'planet\n',
                 'hidden': '',
                 'hint': 'print(max(words, key=len))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print the total length of all the words using sum and a generator.',
                 'starter': 'words = ["sun", "planet"]\n',
                 'expected': '9\n',
                 'hidden': '',
                 'hint': 'print(sum(len(w) for w in words))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Write has_negative(numbers) that returns True if any number is below zero.',
                 'starter': '# define has_negative here\n',
                 'expected': 'True\nFalse\n',
                 'hidden': 'print(has_negative([1, -2]))\nprint(has_negative([3]))\n',
                 'hint': 'def has_negative(numbers):\n    return any(n < 0 for n in numbers)',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Write all_short(words) returning True when every word has at most 4 letters.',
                 'starter': '# define all_short here\n',
                 'expected': 'True\nFalse\n',
                 'hidden': 'print(all_short(["sun", "moon"]))\nprint(all_short(["planet"]))\n',
                 'hint': 'def all_short(words):\n    return all(len(w) <= 4 for w in words)',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print how many words start with s, using sum over a generator of booleans.',
                 'starter': 'words = ["sun", "moon", "star"]\n',
                 'expected': '2\n',
                 'hidden': '',
                 'hint': 'print(sum(w.startswith("s") for w in words))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': "Write total_price(cart) that sums price times quantity over the cart's dicts.",
                 'starter': '# define total_price here\n',
                 'expected': '11\n',
                 'hidden': 'print(total_price([{"price": 2, "qty": 3}, {"price": 5, "qty": 1}]))\n',
                 'hint': 'def total_price(cart):\n    return sum(item["price"] * item["qty"] for item in cart)',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'},
                {'brief': 'Print the smallest word length using min and a generator.',
                 'starter': 'words = ["planet", "sun", "moon"]\n',
                 'expected': '3\n',
                 'hidden': '',
                 'hint': 'print(min(len(w) for w in words))',
                 'tip': 'sum(x for x in items), any(...), all(...), max(items, key=...).'}]},
    # add your own drills here
]
