WORLD = {'name': 'Lists & loops', 'title': 'indexing, slicing, for, range, accumulating, while'}

# A drill is one concept shown ten different ways. Each round is its own
# small task with its own brief, starter, expected output and hint.
DRILLS = [
    {'id': 's4-1',
     'title': 'Index and slice',
     'brief': 'Reaching into a list: one item, from the back, a slice, a list inside a list.',
     'lesson': 'A list keeps items in order. Positions start at 0: items[0] is the first, items[1] the second. '
               'Negative positions count from the end: items[-1] is the last. A slice items[a:b] gives a smaller '
               'list from position a up to but not including b; leave one side empty for the start or the end. A '
               'list can hold other lists: rows[1][0] is the first item of the second row.  Example: ["a", "b", '
               '"c"][1] is "b", [1, 2, 3, 4][1:3] is [2, 3]',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['lists', 'indexing', 'slicing', 'nested'],
     'rounds': [{'brief': 'Print the first item of the list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': 'Mercury\n',
                 'hidden': '',
                 'hint': 'print(planets[0])',
                 'tip': 'the first item is at position 0: planets[0].'},
                {'brief': 'Print the third item of the list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': 'Earth\n',
                 'hidden': '',
                 'hint': 'print(planets[2])',
                 'tip': 'counting starts at 0, so the third item is planets[2].'},
                {'brief': 'Print the last item of the list, without counting how long it is.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': 'Mars\n',
                 'hidden': '',
                 'hint': 'print(planets[-1])',
                 'tip': 'a negative position counts from the end: [-1] is the last item, [-2] the one before.'},
                {'brief': 'Print how many items the list has.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': '4\n',
                 'hidden': '',
                 'hint': 'print(len(planets))',
                 'tip': 'len(list) is the number of items.'},
                {'brief': 'Print the first two items as a list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': "['Mercury', 'Venus']\n",
                 'hidden': '',
                 'hint': 'print(planets[0:2])',
                 'tip': 'a slice [start:stop] takes from start up to but not including stop: [0:2] is items 0 '
                        'and 1.'},
                {'brief': 'Print everything from the third item on, as a list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': "['Earth', 'Mars']\n",
                 'hidden': '',
                 'hint': 'print(planets[2:])',
                 'tip': 'leave the stop empty to go to the end: [2:].'},
                {'brief': 'Print the last two items as a list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth", "Mars"]\n',
                 'expected': "['Earth', 'Mars']\n",
                 'hidden': '',
                 'hint': 'print(planets[-2:])',
                 'tip': '[-2:] means: from the second-to-last item to the end.'},
                {'brief': 'Change the second item to Neptune, then print the list.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth"]\n',
                 'expected': "['Mercury', 'Neptune', 'Earth']\n",
                 'hidden': '',
                 'hint': 'planets[1] = "Neptune"\nprint(planets)',
                 'tip': 'you can assign to a position: planets[1] = ...'},
                {'brief': 'Print the second number of the second row.',
                 'starter': 'rows = [[1, 2, 3], [4, 5, 6]]\n',
                 'expected': '5\n',
                 'hidden': '',
                 'hint': 'print(rows[1][1])',
                 'tip': 'a list inside a list: rows[1] is the second row, then [1] picks inside it.'},
                {'brief': 'Print the last letter of the first word in the list.',
                 'starter': 'words = ["orbit", "comet"]\n',
                 'expected': 't\n',
                 'hidden': '',
                 'hint': 'print(words[0][-1])',
                 'tip': 'index twice: words[0] is the word, then [-1] is its last letter.'}]},
    {'id': 's4-2',
     'title': 'For over a list',
     'brief': 'Doing something with each item.',
     'lesson': 'A for loop repeats a block once per item: for item in items: and then the indented body, where '
               'item is the current value.  Example: for word in words:  print(word)',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['for', 'lists'],
     'rounds': [{'brief': 'Print each planet on its own line.',
                 'starter': 'planets = ["Mercury", "Venus", "Earth"]\n',
                 'expected': 'Mercury\nVenus\nEarth\n',
                 'hidden': '',
                 'hint': 'for planet in planets:\n    print(planet)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each number doubled, one per line.',
                 'starter': 'numbers = [3, 8, 12]\n',
                 'expected': '6\n16\n24\n',
                 'hidden': '',
                 'hint': 'for n in numbers:\n    print(n * 2)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each word in upper case, one per line.',
                 'starter': 'words = ["go", "up"]\n',
                 'expected': 'GO\nUP\n',
                 'hidden': '',
                 'hint': 'for word in words:\n    print(word.upper())',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each name with Hello in front, one per line.',
                 'starter': 'names = ["Kim", "Sam"]\n',
                 'expected': 'Hello Kim\nHello Sam\n',
                 'hidden': '',
                 'hint': 'for name in names:\n    print("Hello", name)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print the length of each word, one per line.',
                 'starter': 'words = ["sun", "planet", "galaxy"]\n',
                 'expected': '3\n6\n6\n',
                 'hidden': '',
                 'hint': 'for word in words:\n    print(len(word))',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print only the numbers above 10, one per line.',
                 'starter': 'numbers = [4, 15, 9, 22]\n',
                 'expected': '15\n22\n',
                 'hidden': '',
                 'hint': 'for n in numbers:\n    if n > 10:\n        print(n)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each item with its price as item: price, one per line.',
                 'starter': 'items = ["tea", "cake"]\nprices = [2, 4]\n',
                 'expected': 'tea: 2\ncake: 4\n',
                 'hidden': '',
                 'hint': 'for item, price in zip(items, prices):\n    print(f"{item}: {price}")',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print the items in reverse order, one per line.',
                 'starter': 'items = ["a", "b", "c"]\n',
                 'expected': 'c\nb\na\n',
                 'hidden': '',
                 'hint': 'for item in reversed(items):\n    print(item)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each letter of the word on its own line.',
                 'starter': 'word = "sky"\n',
                 'expected': 's\nk\ny\n',
                 'hidden': '',
                 'hint': 'for letter in word:\n    print(letter)',
                 'tip': 'for item in items: then the indented body uses item.'},
                {'brief': 'Print each pair from the list of pairs as x and y, like 1 2, one per line.',
                 'starter': 'pairs = [(1, 2), (5, 9)]\n',
                 'expected': '1 2\n5 9\n',
                 'hidden': '',
                 'hint': 'for x, y in pairs:\n    print(x, y)',
                 'tip': 'for item in items: then the indented body uses item.'}]},
    {'id': 's4-3',
     'title': 'Range and enumerate',
     'brief': 'Counting loops and knowing the position.',
     'lesson': 'range(5) counts 0 to 4, range(1, 6) counts 1 to 5, range(2, 11, 2) steps by 2. enumerate(items) '
               'gives you the position and the item together.  Example: for i, item in enumerate(items, '
               'start=1):',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['range', 'enumerate'],
     'rounds': [{'brief': 'Print the numbers 0 to 4, one per line, using range.',
                 'starter': '',
                 'expected': '0\n1\n2\n3\n4\n',
                 'hidden': '',
                 'hint': 'for i in range(5):\n    print(i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the numbers 1 to 5, one per line.',
                 'starter': '',
                 'expected': '1\n2\n3\n4\n5\n',
                 'hidden': '',
                 'hint': 'for i in range(1, 6):\n    print(i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the even numbers from 2 to 10.',
                 'starter': '',
                 'expected': '2\n4\n6\n8\n10\n',
                 'hidden': '',
                 'hint': 'for i in range(2, 11, 2):\n    print(i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print a countdown from 5 to 1.',
                 'starter': '',
                 'expected': '5\n4\n3\n2\n1\n',
                 'hidden': '',
                 'hint': 'for i in range(5, 0, -1):\n    print(i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the word three times, using range.',
                 'starter': 'word = "hey"\n',
                 'expected': 'hey\nhey\nhey\n',
                 'hidden': '',
                 'hint': 'for i in range(3):\n    print(word)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print each item with its position starting at 0, like 0 tea.',
                 'starter': 'items = ["tea", "milk"]\n',
                 'expected': '0 tea\n1 milk\n',
                 'hidden': '',
                 'hint': 'for i, item in enumerate(items):\n    print(i, item)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print each item numbered from 1, like 1. tea.',
                 'starter': 'items = ["tea", "milk", "jam"]\n',
                 'expected': '1. tea\n2. milk\n3. jam\n',
                 'hidden': '',
                 'hint': 'for i, item in enumerate(items, start=1):\n    print(f"{i}. {item}")',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the sum of the numbers from 1 to n.',
                 'starter': 'n = 10\n',
                 'expected': '55\n',
                 'hidden': '',
                 'hint': 'total = 0\nfor i in range(1, n + 1):\n    total = total + i\nprint(total)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the squares of 1 to 4, one per line.',
                 'starter': '',
                 'expected': '1\n4\n9\n16\n',
                 'hidden': '',
                 'hint': 'for i in range(1, 5):\n    print(i * i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'},
                {'brief': 'Print the positions (starting at 0) of every word longer than 3 letters.',
                 'starter': 'words = ["hi", "moon", "a", "stars"]\n',
                 'expected': '1\n3\n',
                 'hidden': '',
                 'hint': 'for i, word in enumerate(words):\n    if len(word) > 3:\n        print(i)',
                 'tip': 'range(start, stop, step) counts; enumerate(items, start=1) gives position and item.'}]},
    {'id': 's4-4',
     'title': 'Accumulating',
     'brief': 'Building a total, a count, a best value or a list inside a loop.',
     'lesson': 'To build a total, a count or a best value, start a variable before the loop, change it inside '
               'the loop, and return or print it after. result.append(x) adds to a list.  Example: total = 0, '
               'then inside the loop total = total + n',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['for', 'accumulate', 'append'],
     'rounds': [{'brief': 'Write total(numbers) that returns the sum with a loop, not sum().',
                 'starter': '# define total here\n',
                 'expected': '15\n',
                 'hidden': 'print(total([4, 5, 6]))\n',
                 'hint': 'def total(numbers):\n'
                         '    result = 0\n'
                         '    for n in numbers:\n'
                         '        result = result + n\n'
                         '    return result',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write count_even(numbers) that returns how many numbers are even.',
                 'starter': '# define count_even here\n',
                 'expected': '3\n',
                 'hidden': 'print(count_even([2, 3, 4, 7, 8]))\n',
                 'hint': 'def count_even(numbers):\n'
                         '    count = 0\n'
                         '    for n in numbers:\n'
                         '        if n % 2 == 0:\n'
                         '            count = count + 1\n'
                         '    return count',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write biggest(numbers) that returns the largest without max().',
                 'starter': '# define biggest here\n',
                 'expected': '42\n',
                 'hidden': 'print(biggest([5, 42, 17]))\n',
                 'hint': 'def biggest(numbers):\n'
                         '    best = numbers[0]\n'
                         '    for n in numbers:\n'
                         '        if n > best:\n'
                         '            best = n\n'
                         '    return best',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write smallest(numbers) that returns the smallest without min().',
                 'starter': '# define smallest here\n',
                 'expected': '3\n',
                 'hidden': 'print(smallest([5, 42, 17, 3]))\n',
                 'hint': 'def smallest(numbers):\n'
                         '    best = numbers[0]\n'
                         '    for n in numbers:\n'
                         '        if n < best:\n'
                         '            best = n\n'
                         '    return best',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write doubles(numbers) that returns a new list with every number doubled.',
                 'starter': '# define doubles here\n',
                 'expected': '[2, 4, 6]\n',
                 'hidden': 'print(doubles([1, 2, 3]))\n',
                 'hint': 'def doubles(numbers):\n'
                         '    result = []\n'
                         '    for n in numbers:\n'
                         '        result.append(n * 2)\n'
                         '    return result',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write evens(numbers) that returns a new list with only the even numbers.',
                 'starter': '# define evens here\n',
                 'expected': '[2, 4, 6]\n',
                 'hidden': 'print(evens([1, 2, 3, 4, 5, 6]))\n',
                 'hint': 'def evens(numbers):\n'
                         '    result = []\n'
                         '    for n in numbers:\n'
                         '        if n % 2 == 0:\n'
                         '            result.append(n)\n'
                         '    return result',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write longest(words) that returns the longest word.',
                 'starter': '# define longest here\n',
                 'expected': 'planet\n',
                 'hidden': 'print(longest(["sun", "planet", "moon"]))\n',
                 'hint': 'def longest(words):\n'
                         '    best = words[0]\n'
                         '    for word in words:\n'
                         '        if len(word) > len(best):\n'
                         '            best = word\n'
                         '    return best',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write joined(words) that returns all the words glued together with a loop and +.',
                 'starter': '# define joined here\n',
                 'expected': 'abc\n',
                 'hidden': 'print(joined(["a", "b", "c"]))\n',
                 'hint': 'def joined(words):\n'
                         '    result = ""\n'
                         '    for word in words:\n'
                         '        result = result + word\n'
                         '    return result',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write average(numbers) that returns the mean using a loop for the total.',
                 'starter': '# define average here\n',
                 'expected': '5.0\n',
                 'hidden': 'print(average([2, 4, 9]))\n',
                 'hint': 'def average(numbers):\n'
                         '    total = 0\n'
                         '    for n in numbers:\n'
                         '        total = total + n\n'
                         '    return total / len(numbers)',
                 'tip': 'start a variable before the loop, update it inside, use it after.'},
                {'brief': 'Write count_letter(words, letter) that returns how many words contain the letter.',
                 'starter': '# define count_letter here\n',
                 'expected': '1\n',
                 'hidden': 'print(count_letter(["sun", "moon", "star"], "o"))\n',
                 'hint': 'def count_letter(words, letter):\n'
                         '    count = 0\n'
                         '    for word in words:\n'
                         '        if letter in word:\n'
                         '            count = count + 1\n'
                         '    return count',
                 'tip': 'start a variable before the loop, update it inside, use it after.'}]},
    {'id': 's4-5',
     'title': 'While loops',
     'brief': 'Looping until a condition stops being true.',
     'lesson': 'while repeats as long as its condition stays true, so something inside must move it toward '
               'false. break leaves the loop early, continue skips to the next turn.  Example: while n > 0:  n = '
               'n - 1',
     'starter': '',
     'expected': '',
     'hidden': '',
     'hint': '',
     'concepts': ['while', 'break'],
     'rounds': [{'brief': 'Print 1, 2, 3 using a while loop.',
                 'starter': 'n = 1\n',
                 'expected': '1\n2\n3\n',
                 'hidden': '',
                 'hint': 'while n <= 3:\n    print(n)\n    n = n + 1',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Keep halving n and printing it while it is above 1.',
                 'starter': 'n = 40\n',
                 'expected': '20\n10\n5\n2\n1\n',
                 'hidden': '',
                 'hint': 'while n > 1:\n    n = n // 2\n    print(n)',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Print a countdown from n to 1 with a while loop.',
                 'starter': 'n = 4\n',
                 'expected': '4\n3\n2\n1\n',
                 'hidden': '',
                 'hint': 'while n > 0:\n    print(n)\n    n = n - 1',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Write countdown(n) that returns a list from n down to 1 using while.',
                 'starter': '# define countdown here\n',
                 'expected': '[3, 2, 1]\n',
                 'hidden': 'print(countdown(3))\n',
                 'hint': 'def countdown(n):\n'
                         '    result = []\n'
                         '    while n > 0:\n'
                         '        result.append(n)\n'
                         '        n = n - 1\n'
                         '    return result',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Add 7 to total until it is at least 30, then print total.',
                 'starter': 'total = 0\n',
                 'expected': '35\n',
                 'hidden': '',
                 'hint': 'while total < 30:\n    total = total + 7\nprint(total)',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Print the numbers 1 to 10 but stop the loop with break when you reach 4.',
                 'starter': 'n = 0\n',
                 'expected': '1\n2\n3\n',
                 'hidden': '',
                 'hint': 'while n < 10:\n    n = n + 1\n    if n == 4:\n        break\n    print(n)',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Write digits(n) that returns how many digits n has, using while and floor division by '
                          '10.',
                 'starter': '# define digits here\n',
                 'expected': '4\n',
                 'hidden': 'print(digits(4096))\n',
                 'hint': 'def digits(n):\n'
                         '    count = 0\n'
                         '    while n > 0:\n'
                         '        n = n // 10\n'
                         '        count = count + 1\n'
                         '    return count',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Print the powers of 2 below 50, one per line.',
                 'starter': 'p = 1\n',
                 'expected': '1\n2\n4\n8\n16\n32\n',
                 'hidden': '',
                 'hint': 'while p < 50:\n    print(p)\n    p = p * 2',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Print the numbers from 1 to 6 but skip 3, using continue.',
                 'starter': 'n = 0\n',
                 'expected': '1\n2\n4\n5\n6\n',
                 'hidden': '',
                 'hint': 'while n < 6:\n    n = n + 1\n    if n == 3:\n        continue\n    print(n)',
                 'tip': 'while condition: and make sure something inside changes the condition.'},
                {'brief': 'Write first_over(numbers, limit) returning the first number above limit, looping with '
                          'an index and while.',
                 'starter': '# define first_over here\n',
                 'expected': '12\n',
                 'hidden': 'print(first_over([3, 8, 12, 20], 10))\n',
                 'hint': 'def first_over(numbers, limit):\n'
                         '    i = 0\n'
                         '    while numbers[i] <= limit:\n'
                         '        i = i + 1\n'
                         '    return numbers[i]',
                 'tip': 'while condition: and make sure something inside changes the condition.'}]},
    # add your own drills here
]
