WORLD = {"name": "Basics", "title": "print, variables, numbers, functions"}

LEVELS = [
    {
        "id": "1-1",
        "title": "First word",
        "brief": "Print the word dive.",
        "starter": "",
        "expected": "dive\n",
        "hidden": "",
        "hint": 'print("dive")',
        "concepts": ["print"],
    },
    {
        "id": "1-2",
        "title": "Three lines",
        "brief": "Print the city, the year and the temperature, each on its own line.",
        "starter": 'city = "Antwerp"\nyear = 2026\ntemp = 18.5\n',
        "expected": "Antwerp\n2026\n18.5\n",
        "hidden": "",
        "hint": "print(city)\nprint(year)\nprint(temp)",
        "concepts": ["print", "variables"],
    },
    {
        "id": "1-3",
        "title": "Rectangle",
        "brief": "Print the area of a rectangle with this width and height.",
        "starter": "width = 7\nheight = 3\n",
        "expected": "21\n",
        "hidden": "",
        "hint": "print(width * height)",
        "concepts": ["arithmetic", "print"],
    },
    {
        "id": "1-4",
        "title": "Minutes and seconds",
        "brief": "Print how many whole minutes fit in seconds, then how many seconds are left over.",
        "starter": "seconds = 500\n",
        "expected": "8\n20\n",
        "hidden": "",
        "hint": "print(seconds // 60)\nprint(seconds % 60)",
        "concepts": ["floor division", "modulo"],
    },
    {
        "id": "1-5",
        "title": "Powers",
        "brief": "Print base to the power of 10, then the square root of base rounded to 3 decimals.",
        "starter": "base = 2\n",
        "expected": "1024\n1.414\n",
        "hidden": "",
        "hint": "print(base ** 10)\nprint(round(base ** 0.5, 3))",
        "concepts": ["power", "round"],
    },
    {
        "id": "1-6",
        "title": "Triple",
        "brief": "Write a function triple(x) that returns x times three. Do not print inside it.",
        "starter": "# define triple here\n",
        "expected": "12\n7.5\n",
        "hidden": "print(triple(4))\nprint(triple(2.5))\n",
        "hint": "def triple(x):\n    return x * 3",
        "concepts": ["functions", "return"],
    },
    {
        "id": "1-7",
        "title": "Sticker",
        "brief": 'Write label(name, suffix="!") that returns the name with the suffix glued on the end.',
        "starter": "# define label here\n",
        "expected": "Ada!\nKim?\n",
        "hidden": 'print(label("Ada"))\nprint(label("Kim", "?"))\n',
        "hint": 'def label(name, suffix="!"):\n    return name + suffix',
        "concepts": ["functions", "default arguments", "strings"],
    },
    {
        "id": "1-8",
        "title": "Circle",
        "brief": "Write circle_area(r) using 3.14159, then print the area for r = 2.5 rounded to 1 decimal.",
        "starter": "# define circle_area here, then print the rounded area for r = 2.5\n",
        "expected": "19.6\n",
        "hidden": "",
        "hint": "def circle_area(r):\n    return 3.14159 * r * r\n\nprint(round(circle_area(2.5), 1))",
        "concepts": ["functions", "return", "round", "arithmetic"],
    },
]
