WORLD = {"name": "Flow", "title": "booleans, comparisons, if / elif / else"}

LEVELS = [
    {
        "id": "2-1",
        "title": "Smaller",
        "brief": "Print whether a is smaller than b.",
        "starter": "a = 3\nb = 8\n",
        "expected": "True\n",
        "hidden": "",
        "hint": "print(a < b)",
        "concepts": ["booleans", "comparisons"],
    },
    {
        "id": "2-2",
        "title": "Warm or cold",
        "brief": 'Print "warm" if temp is 20 or more, otherwise print "cold".',
        "starter": "temp = 12\n",
        "expected": "cold\n",
        "hidden": "",
        "hint": 'if temp >= 20:\n    print("warm")\nelse:\n    print("cold")',
        "concepts": ["if", "else"],
    },
    {
        "id": "2-3",
        "title": "Odd check",
        "brief": "Write is_odd(n) that returns True when n is odd.",
        "starter": "# define is_odd here\n",
        "expected": "True\nFalse\nFalse\n",
        "hidden": "print(is_odd(3))\nprint(is_odd(8))\nprint(is_odd(0))\n",
        "hint": "def is_odd(n):\n    return n % 2 == 1",
        "concepts": ["booleans", "modulo", "functions"],
    },
    {
        "id": "2-4",
        "title": "Sign words",
        "brief": 'Print "negative", "zero" or "positive" depending on n.',
        "starter": "n = -4\n",
        "expected": "negative\n",
        "hidden": "",
        "hint": 'if n < 0:\n    print("negative")\nelif n == 0:\n    print("zero")\nelse:\n    print("positive")',
        "concepts": ["if", "elif", "else"],
    },
    {
        "id": "2-5",
        "title": "Discount",
        "brief": "Write can_discount(age, member) that returns True if age is 65 or more, or member is True.",
        "starter": "# define can_discount here\n",
        "expected": "True\nTrue\nFalse\n",
        "hidden": "print(can_discount(70, False))\nprint(can_discount(30, True))\nprint(can_discount(30, False))\n",
        "hint": "def can_discount(age, member):\n    return age >= 65 or member",
        "concepts": ["booleans", "or", "functions"],
    },
    {
        "id": "2-6",
        "title": "Shirt size",
        "brief": 'Write size(cm): "S" below 170, "M" below 180, "L" below 190, else "XL".',
        "starter": "# define size here\n",
        "expected": "S\nM\nL\nXL\n",
        "hidden": "print(size(165))\nprint(size(175))\nprint(size(189))\nprint(size(200))\n",
        "hint": 'def size(cm):\n    if cm < 170:\n        return "S"\n    elif cm < 180:\n        return "M"\n    elif cm < 190:\n        return "L"\n    else:\n        return "XL"',
        "concepts": ["if", "elif", "else", "functions", "return"],
    },
    {
        "id": "2-7",
        "title": "Ticket price",
        "brief": "Write price(age): 0 under 4, 5 under 12, 12 under 65, and 7 from 65 up.",
        "starter": "# define price here\n",
        "expected": "0\n5\n12\n7\n",
        "hidden": "print(price(2))\nprint(price(8))\nprint(price(30))\nprint(price(70))\n",
        "hint": "def price(age):\n    if age < 4:\n        return 0\n    elif age < 12:\n        return 5\n    elif age < 65:\n        return 12\n    else:\n        return 7",
        "concepts": ["if", "elif", "else", "functions"],
    },
    {
        "id": "2-8",
        "title": "Water state",
        "brief": 'Write state(temp): "ice" at 0 or below, "steam" at 100 or above, otherwise "water".',
        "starter": "# define state here\n",
        "expected": "ice\nwater\nsteam\n",
        "hidden": "print(state(-5))\nprint(state(20))\nprint(state(100))\n",
        "hint": 'def state(temp):\n    if temp <= 0:\n        return "ice"\n    if temp >= 100:\n        return "steam"\n    return "water"',
        "concepts": ["if", "comparisons", "functions", "return"],
    },
]
