WORLD = {"name": "Classes", "title": "class, __init__, methods, __str__"}

LEVELS = [
    {
        "id": "8-1",
        "title": "A cat",
        "brief": "Write a class Cat with an __init__ that stores name, and speak() that returns name plus \" says meow\".",
        "starter": "# define Cat here\n",
        "expected": "Mia says meow\n",
        "hidden": 'print(Cat("Mia").speak())\n',
        "hint": 'class Cat:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        return self.name + " says meow"',
        "concepts": ["classes", "__init__", "methods"],
    },
    {
        "id": "8-2",
        "title": "Thermostat",
        "brief": "Write a class Thermostat starting at temp 20, with up() and down() that change temp by one degree.",
        "starter": "# define Thermostat here\n",
        "expected": "21\n",
        "hidden": "t = Thermostat()\nt.up()\nt.up()\nt.down()\nprint(t.temp)\n",
        "hint": "class Thermostat:\n    def __init__(self):\n        self.temp = 20\n\n    def up(self):\n        self.temp = self.temp + 1\n\n    def down(self):\n        self.temp = self.temp - 1",
        "concepts": ["classes", "attributes", "methods"],
    },
    {
        "id": "8-3",
        "title": "Box",
        "brief": "Write a class Box(w, h, d) whose __str__ returns \"w x h x d\" and whose volume() returns the product.",
        "starter": "# define Box here\n",
        "expected": "2 x 3 x 4\n24\n",
        "hidden": "b = Box(2, 3, 4)\nprint(b)\nprint(b.volume())\n",
        "hint": 'class Box:\n    def __init__(self, w, h, d):\n        self.w = w\n        self.h = h\n        self.d = d\n\n    def __str__(self):\n        return f"{self.w} x {self.h} x {self.d}"\n\n    def volume(self):\n        return self.w * self.h * self.d',
        "concepts": ["classes", "__str__", "methods", "f-strings"],
    },
    {
        "id": "8-4",
        "title": "Shared counter",
        "brief": "Write class Track with a class attribute plays_total, an instance attribute plays, and play() that adds one to both.",
        "starter": "# define Track here\n",
        "expected": "2 1 3\n",
        "hidden": "a = Track()\nb = Track()\na.play()\na.play()\nb.play()\nprint(a.plays, b.plays, Track.plays_total)\n",
        "hint": "class Track:\n    plays_total = 0\n\n    def __init__(self):\n        self.plays = 0\n\n    def play(self):\n        self.plays = self.plays + 1\n        Track.plays_total = Track.plays_total + 1",
        "concepts": ["classes", "class attributes", "methods"],
    },
    {
        "id": "8-5",
        "title": "Inheritance",
        "brief": 'Write Animal(name) with describe() returning "animal: name", and Dog(Animal) whose describe() returns "dog: name".',
        "starter": "# define Animal and Dog here\n",
        "expected": "animal: x\ndog: Rex\nTrue\n",
        "hidden": 'print(Animal("x").describe())\nprint(Dog("Rex").describe())\nprint(isinstance(Dog("Rex"), Animal))\n',
        "hint": 'class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def describe(self):\n        return f"animal: {self.name}"\n\n\nclass Dog(Animal):\n    def describe(self):\n        return f"dog: {self.name}"',
        "concepts": ["classes", "inheritance", "override"],
    },
    {
        "id": "8-6",
        "title": "Property",
        "brief": "Write Circle(r) with a property area that returns 3.14159 times r squared, rounded to 2 decimals.",
        "starter": "# define Circle here\n",
        "expected": "3.14\n12.57\n",
        "hidden": "print(Circle(1).area)\nprint(Circle(2).area)\n",
        "hint": "class Circle:\n    def __init__(self, r):\n        self.r = r\n\n    @property\n    def area(self):\n        return round(3.14159 * self.r ** 2, 2)",
        "concepts": ["classes", "property", "round"],
    },
    {
        "id": "8-7",
        "title": "Equal points",
        "brief": 'Write Point(x, y) with __eq__ comparing both numbers and __repr__ returning "Point(x, y)".',
        "starter": "# define Point here\n",
        "expected": "True\nFalse\nPoint(3, 4)\n",
        "hidden": "print(Point(1, 2) == Point(1, 2))\nprint(Point(1, 2) == Point(2, 1))\nprint(Point(3, 4))\n",
        "hint": 'class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\n\n    def __repr__(self):\n        return f"Point({self.x}, {self.y})"',
        "concepts": ["classes", "__eq__", "__repr__"],
    },
    {
        "id": "8-8",
        "title": "Bank account",
        "brief": "Write BankAccount(balance) with deposit(n), withdraw(n) that returns False instead of going negative, and __str__ \"balance: n\". Then SavingsAccount(BankAccount) with apply_interest(rate).",
        "starter": "# define BankAccount and SavingsAccount here\n",
        "expected": "False\nbalance: 225.0\n",
        "hidden": "a = SavingsAccount(100)\na.deposit(50)\nprint(a.withdraw(500))\na.apply_interest(0.5)\nprint(a)\n",
        "hint": 'class BankAccount:\n    def __init__(self, balance):\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance = self.balance + amount\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            return False\n        self.balance = self.balance - amount\n        return True\n\n    def __str__(self):\n        return f"balance: {self.balance}"\n\n\nclass SavingsAccount(BankAccount):\n    def apply_interest(self, rate):\n        self.balance = self.balance * (1 + rate)',
        "concepts": ["classes", "inheritance", "__str__", "if"],
    },
    # add your own levels here
]
