WORLD = {"name": "Dicts", "title": "keys, values, items, counting"}

LEVELS = [
    {
        "id": "5-1",
        "title": "Capital",
        "brief": "Print the capital of Spain from the dict.",
        "starter": 'capitals = {"Belgium": "Brussels", "Spain": "Madrid"}\n',
        "expected": "Madrid\n",
        "hidden": "",
        "hint": 'print(capitals["Spain"])',
        "concepts": ["dicts"],
    },
    {
        "id": "5-2",
        "title": "In stock",
        "brief": "Print the names of the fruits that have more than 0 in stock, one per line, in order.",
        "starter": 'stock = {"apple": 3, "pear": 0, "kiwi": 5}\n',
        "expected": "apple\nkiwi\n",
        "hidden": "",
        "hint": "for name, count in stock.items():\n    if count > 0:\n        print(name)",
        "concepts": ["dicts", "for", "if"],
    },
    {
        "id": "5-3",
        "title": "Letter count",
        "brief": "Write count_letters(text) that returns a dict from each letter to how often it appears, skipping spaces.",
        "starter": "# define count_letters here\n",
        "expected": "{'a': 2, 'b': 2}\n",
        "hidden": 'print(count_letters("aab b"))\n',
        "hint": 'def count_letters(text):\n    counts = {}\n    for letter in text:\n        if letter != " ":\n            counts[letter] = counts.get(letter, 0) + 1\n    return counts',
        "concepts": ["dicts", "for", "if", "functions"],
    },
    {
        "id": "5-4",
        "title": "Safe lookup",
        "brief": 'Print the phone number from the dict, or "n/a" when there is none, without an error.',
        "starter": 'user = {"name": "Ada"}\n',
        "expected": "n/a\n",
        "hidden": "",
        "hint": 'print(user.get("phone", "n/a"))',
        "concepts": ["dicts", "get"],
    },
    {
        "id": "5-5",
        "title": "Add and remove",
        "brief": 'Add the city Madrid to the dict, remove the age, then print the dict.',
        "starter": 'user = {"name": "Ada", "age": 36}\n',
        "expected": "{'name': 'Ada', 'city': 'Madrid'}\n",
        "hidden": "",
        "hint": 'user["city"] = "Madrid"\ndel user["age"]\nprint(user)',
        "concepts": ["dicts", "del"],
    },
    {
        "id": "5-6",
        "title": "Order totals",
        "brief": "Write totals(orders) that turns a list of (fruit, quantity) pairs into a dict of total quantity per fruit.",
        "starter": "# define totals here\n",
        "expected": "{'apple': 5, 'pear': 1}\n",
        "hidden": 'print(totals([("apple", 2), ("pear", 1), ("apple", 3)]))\n',
        "hint": "def totals(orders):\n    result = {}\n    for fruit, quantity in orders:\n        result[fruit] = result.get(fruit, 0) + quantity\n    return result",
        "concepts": ["dicts", "tuples", "for", "get", "functions"],
    },
    {
        "id": "5-7",
        "title": "Unique and sorted",
        "brief": "Write unique_sorted(words) that returns the different words in alphabetical order as a list.",
        "starter": "# define unique_sorted here\n",
        "expected": "['a', 'b', 'c']\n",
        "hidden": 'print(unique_sorted(["b", "a", "b", "c"]))\n',
        "hint": "def unique_sorted(words):\n    return sorted(set(words))",
        "concepts": ["sets", "sorted", "functions"],
    },
    {
        "id": "5-8",
        "title": "Nested data",
        "brief": "Print each user's name and how many tags they have, like A 2, one per line.",
        "starter": 'data = {"users": [{"name": "A", "tags": ["x", "y"]}, {"name": "B", "tags": []}]}\n',
        "expected": "A 2\nB 0\n",
        "hidden": "",
        "hint": 'for user in data["users"]:\n    print(user["name"], len(user["tags"]))',
        "concepts": ["dicts", "lists", "for", "len"],
    },
    # add your own levels here
]
