WORLD = {"name": "Lists & loops", "title": "lists, for, while, reversed"}

LEVELS = [
    {
        "id": "4-1",
        "title": "Backwards",
        "brief": "Print each colour on its own line, last one first.",
        "starter": 'colours = ["red", "green", "blue"]\n',
        "expected": "blue\ngreen\nred\n",
        "hidden": "",
        "hint": "for colour in reversed(colours):\n    print(colour)",
        "concepts": ["lists", "for", "reversed"],
    },
    {
        "id": "4-2",
        "title": "Biggest",
        "brief": "Write biggest(numbers) that returns the largest number, using a loop, not max().",
        "starter": "# define biggest here\n",
        "expected": "9\n-1\n",
        "hidden": "print(biggest([3, 9, 2]))\nprint(biggest([-5, -1]))\n",
        "hint": "def biggest(numbers):\n    best = numbers[0]\n    for n in numbers:\n        if n > best:\n            best = n\n    return best",
        "concepts": ["lists", "for", "if", "functions"],
    },
    {
        "id": "4-3",
        "title": "Countdown",
        "brief": 'Write countdown(n) that returns a list counting from n down to 1, then the word "go". Use a while loop.',
        "starter": "# define countdown here\n",
        "expected": "[3, 2, 1, 'go']\n",
        "hidden": "print(countdown(3))\n",
        "hint": 'def countdown(n):\n    result = []\n    while n > 0:\n        result.append(n)\n        n = n - 1\n    result.append("go")\n    return result',
        "concepts": ["lists", "while", "append", "functions"],
    },
    {
        "id": "4-4",
        "title": "Even steps",
        "brief": "Print the even numbers from 2 to 10, one per line, using range.",
        "starter": "",
        "expected": "2\n4\n6\n8\n10\n",
        "hidden": "",
        "hint": "for n in range(2, 11, 2):\n    print(n)",
        "concepts": ["for", "range"],
    },
    {
        "id": "4-5",
        "title": "Numbered",
        "brief": "Print each score with its position starting at 1, like 1. 72, one per line.",
        "starter": "scores = [72, 95, 48]\n",
        "expected": "1. 72\n2. 95\n3. 48\n",
        "hidden": "",
        "hint": 'for position, score in enumerate(scores, start=1):\n    print(f"{position}. {score}")',
        "concepts": ["for", "enumerate", "f-strings"],
    },
    {
        "id": "4-6",
        "title": "Passing scores",
        "brief": "Write passing(scores) that returns the scores of 50 or more, highest first.",
        "starter": "# define passing here\n",
        "expected": "[95, 88, 72, 61]\n",
        "hidden": "print(passing([72, 95, 48, 88, 61]))\n",
        "hint": "def passing(scores):\n    result = []\n    for score in scores:\n        if score >= 50:\n            result.append(score)\n    result.sort(reverse=True)\n    return result",
        "concepts": ["lists", "for", "if", "sort", "functions"],
    },
    {
        "id": "4-7",
        "title": "Side by side",
        "brief": "Print each name with its age, like Ann is 30, one per line, using zip.",
        "starter": 'names = ["Ann", "Bo"]\nages = [30, 25]\n',
        "expected": "Ann is 30\nBo is 25\n",
        "hidden": "",
        "hint": 'for name, age in zip(names, ages):\n    print(f"{name} is {age}")',
        "concepts": ["for", "zip", "f-strings"],
    },
    {
        "id": "4-8",
        "title": "First repeat",
        "brief": "Write first_repeat(items) that returns the first value that appears a second time, or None.",
        "starter": "# define first_repeat here\n",
        "expected": "3\nNone\n",
        "hidden": "print(first_repeat([3, 5, 3, 5]))\nprint(first_repeat([1, 2]))\n",
        "hint": "def first_repeat(items):\n    seen = []\n    for item in items:\n        if item in seen:\n            return item\n        seen.append(item)\n    return None",
        "concepts": ["lists", "for", "in", "return", "None"],
    },
    # add your own levels here
]
