WORLD = {"name": "Functions", "title": "defaults, keyword args, recursion"}

LEVELS = [
    {
        "id": "6-1",
        "title": "Split the bill",
        "brief": "Write split(total, people=2) that returns each person's share rounded to 2 decimals.",
        "starter": "# define split here\n",
        "expected": "5.0\n33.33\n",
        "hidden": "print(split(10))\nprint(split(100, people=3))\n",
        "hint": "def split(total, people=2):\n    return round(total / people, 2)",
        "concepts": ["functions", "default arguments", "keyword arguments", "round"],
    },
    {
        "id": "6-2",
        "title": "Average",
        "brief": "Write average(numbers) that returns the mean, or 0 for an empty list.",
        "starter": "# define average here\n",
        "expected": "5.0\n0\n",
        "hidden": "print(average([2, 4, 9]))\nprint(average([]))\n",
        "hint": "def average(numbers):\n    if len(numbers) == 0:\n        return 0\n    return sum(numbers) / len(numbers)",
        "concepts": ["functions", "if", "lists", "return"],
    },
    {
        "id": "6-3",
        "title": "Power by hand",
        "brief": "Write power(base, exponent) using recursion, without **. power(x, 0) is 1.",
        "starter": "# define power here\n",
        "expected": "1\n32\n27\n",
        "hidden": "print(power(2, 0))\nprint(power(2, 5))\nprint(power(3, 3))\n",
        "hint": "def power(base, exponent):\n    if exponent == 0:\n        return 1\n    return base * power(base, exponent - 1)",
        "concepts": ["functions", "recursion", "if"],
    },
    {
        "id": "6-4",
        "title": "Any amount",
        "brief": "Write total(*nums) that returns the sum of however many numbers it gets.",
        "starter": "# define total here\n",
        "expected": "6\n0\n",
        "hidden": "print(total(1, 2, 3))\nprint(total())\n",
        "hint": "def total(*nums):\n    return sum(nums)",
        "concepts": ["functions", "*args", "sum"],
    },
    {
        "id": "6-5",
        "title": "Options",
        "brief": "Write show(**options) that prints each option as key=value, one per line, in order.",
        "starter": "# define show here\n",
        "expected": "a=1\nb=x\n",
        "hidden": 'show(a=1, b="x")\n',
        "hint": 'def show(**options):\n    for key, value in options.items():\n        print(f"{key}={value}")',
        "concepts": ["functions", "**kwargs", "dicts"],
    },
    {
        "id": "6-6",
        "title": "Shortest first",
        "brief": "Print the words sorted from shortest to longest.",
        "starter": 'words = ["kiwi", "fig", "banana"]\n',
        "expected": "['fig', 'kiwi', 'banana']\n",
        "hidden": "",
        "hint": "print(sorted(words, key=len))",
        "concepts": ["sorted", "key", "functions as values"],
    },
    {
        "id": "6-7",
        "title": "Twice",
        "brief": "Write twice(func, value) that applies the function to the value two times and returns the result.",
        "starter": "# define twice here\n",
        "expected": "7\nA\n",
        "hidden": 'def add3(x):\n    return x + 3\n\nprint(twice(add3, 1))\nprint(twice(str.upper, "a"))\n',
        "hint": "def twice(func, value):\n    return func(func(value))",
        "concepts": ["functions as values", "functions"],
    },
    {
        "id": "6-8",
        "title": "Digit sum",
        "brief": "Write sum_digits(n) using recursion: the last digit plus the digit sum of the rest.",
        "starter": "# define sum_digits here\n",
        "expected": "10\n7\n",
        "hidden": "print(sum_digits(1234))\nprint(sum_digits(7))\n",
        "hint": "def sum_digits(n):\n    if n < 10:\n        return n\n    return n % 10 + sum_digits(n // 10)",
        "concepts": ["recursion", "modulo", "floor division"],
    },
    # add your own levels here
]
