WORLD = {"name": "Errors & files", "title": "try / except, raise, open, with"}

LEVELS = [
    {
        "id": "9-1",
        "title": "Safe int",
        "brief": "Write to_int(text) that returns int(text), or -1 when the text is not a number.",
        "starter": "# define to_int here\n",
        "expected": "42\n-1\n",
        "hidden": 'print(to_int("42"))\nprint(to_int("abc"))\n',
        "hint": "def to_int(text):\n    try:\n        return int(text)\n    except ValueError:\n        return -1",
        "concepts": ["exceptions", "try", "except"],
    },
    {
        "id": "9-2",
        "title": "Shopping list",
        "brief": "Write the items to list.txt one per line, read the file back, then print how many lines it has followed by each line.",
        "starter": 'items = ["milk", "eggs"]\n',
        "expected": "2\nmilk\neggs\n",
        "hidden": "",
        "hint": 'with open("list.txt", "w") as f:\n    for item in items:\n        f.write(item + "\\n")\n\nwith open("list.txt") as f:\n    lines = f.read().splitlines()\n\nprint(len(lines))\nfor line in lines:\n    print(line)',
        "concepts": ["files", "with", "open", "for", "len"],
    },
    {
        "id": "9-3",
        "title": "Age check",
        "brief": 'Write check_age(age) that raises ValueError("too young") below 18 and returns "ok" otherwise.',
        "starter": "# define check_age here\n",
        "expected": "ok\ntoo young\n",
        "hidden": "print(check_age(20))\ntry:\n    check_age(10)\nexcept ValueError as error:\n    print(error)\n",
        "hint": 'def check_age(age):\n    if age < 18:\n        raise ValueError("too young")\n    return "ok"',
        "concepts": ["exceptions", "raise", "if", "functions"],
    },
    {
        "id": "9-4",
        "title": "Always done",
        "brief": 'Write divide(a, b) that returns a / b, or None when b is zero, and prints "done" every time whatever happens.',
        "starter": "# define divide here\n",
        "expected": "done\n2.0\ndone\nNone\n",
        "hidden": "print(divide(6, 3))\nprint(divide(1, 0))\n",
        "hint": 'def divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n    finally:\n        print("done")',
        "concepts": ["try", "except", "finally"],
    },
    {
        "id": "9-5",
        "title": "Your own error",
        "brief": 'Write a class EmptyListError(Exception) and first(items) that raises EmptyListError("empty") for an empty list, else returns the first item.',
        "starter": "# define EmptyListError and first here\n",
        "expected": "4\nempty\n",
        "hidden": "print(first([4, 5]))\ntry:\n    first([])\nexcept EmptyListError as error:\n    print(error)\n",
        "hint": 'class EmptyListError(Exception):\n    pass\n\n\ndef first(items):\n    if len(items) == 0:\n        raise EmptyListError("empty")\n    return items[0]',
        "concepts": ["exceptions", "raise", "classes"],
    },
    {
        "id": "9-6",
        "title": "Read JSON",
        "brief": "Turn the JSON text into a dict with the json module, then print the name and how many langs there are.",
        "starter": "text = '{\"name\": \"Ada\", \"langs\": [\"py\", \"js\"]}'\n",
        "expected": "Ada\n2\n",
        "hidden": "",
        "hint": 'import json\n\ndata = json.loads(text)\nprint(data["name"])\nprint(len(data["langs"]))',
        "concepts": ["json", "import", "dicts"],
    },
    {
        "id": "9-7",
        "title": "Count lines",
        "brief": "Write the lines to notes.txt, then read the file line by line and print how many lines contain the letter a.",
        "starter": 'lines = ["apple", "kiwi", "banana"]\n',
        "expected": "2\n",
        "hidden": "",
        "hint": 'with open("notes.txt", "w") as f:\n    for line in lines:\n        f.write(line + "\\n")\n\ncount = 0\nwith open("notes.txt") as f:\n    for line in f:\n        if "a" in line:\n            count = count + 1\nprint(count)',
        "concepts": ["files", "with", "for", "in"],
    },
    {
        "id": "9-8",
        "title": "Users file",
        "brief": "Write users_over(path, age) that reads a JSON file with a list of users and returns the names older than age, or an empty list when the file is missing.",
        "starter": "# define users_over here\n",
        "expected": "['A']\n[]\n",
        "hidden": 'import json\nwith open("users.json", "w") as f:\n    json.dump([{"name": "A", "age": 30}, {"name": "B", "age": 12}], f)\nprint(users_over("users.json", 18))\nprint(users_over("missing.json", 18))\n',
        "hint": 'import json\n\n\ndef users_over(path, age):\n    try:\n        with open(path) as f:\n            users = json.load(f)\n    except FileNotFoundError:\n        return []\n    return [user["name"] for user in users if user["age"] > age]',
        "concepts": ["json", "files", "try", "except", "comprehensions"],
    },
    # add your own levels here
]
