WORLD = {"name": "Strings", "title": "len, lower, indexing, f-strings"}

LEVELS = [
    {
        "id": "3-1",
        "title": "Whisper",
        "brief": "Print the word in lower case.",
        "starter": 'word = "LOUD"\n',
        "expected": "loud\n",
        "hidden": "",
        "hint": "print(word.lower())",
        "concepts": ["strings", "methods"],
    },
    {
        "id": "3-2",
        "title": "Initials",
        "brief": "Use an f-string to print both initials with a dot after each (G.H.)",
        "starter": 'first = "Grace"\nlast = "Hopper"\n',
        "expected": "G.H.\n",
        "hidden": "",
        "hint": 'print(f"{first[0]}.{last[0]}.")',
        "concepts": ["strings", "indexing", "f-strings"],
    },
    {
        "id": "3-3",
        "title": "Count vowels",
        "brief": "Write vowels(text) that returns how many of a, e, i, o, u appear, ignoring case.",
        "starter": "# define vowels here\n",
        "expected": "3\n0\n5\n",
        "hidden": 'print(vowels("Banana"))\nprint(vowels("sky"))\nprint(vowels("AEIOU"))\n',
        "hint": 'def vowels(text):\n    count = 0\n    for letter in text.lower():\n        if letter in "aeiou":\n            count = count + 1\n    return count',
        "concepts": ["strings", "for", "if", "functions"],
    },
    {
        "id": "3-4",
        "title": "How long",
        "brief": "Print how many letters the word has.",
        "starter": 'word = "hippopotamus"\n',
        "expected": "12\n",
        "hidden": "",
        "hint": "print(len(word))",
        "concepts": ["strings", "len"],
    },
    {
        "id": "3-5",
        "title": "Slices",
        "brief": "Print the first five characters, then everything from index 7 on.",
        "starter": 's = "Hello, World"\n',
        "expected": "Hello\nWorld\n",
        "hidden": "",
        "hint": "print(s[0:5])\nprint(s[7:])",
        "concepts": ["strings", "slicing"],
    },
    {
        "id": "3-6",
        "title": "Clean email",
        "brief": "Print the email without the spaces around it and in lower case.",
        "starter": 'email = "  Emile.Smith@Mule.digital "\n',
        "expected": "emile.smith@mule.digital\n",
        "hidden": "",
        "hint": "print(email.strip().lower())",
        "concepts": ["strings", "strip", "lower"],
    },
    {
        "id": "3-7",
        "title": "Money",
        "brief": "Write money(amount) that returns the amount with a € in front, thousands separators and 2 decimals.",
        "starter": "# define money here\n",
        "expected": "€1,234,567.89\n€5.00\n",
        "hidden": "print(money(1234567.891))\nprint(money(5))\n",
        "hint": 'def money(amount):\n    return f"€{amount:,.2f}"',
        "concepts": ["f-strings", "formatting", "functions"],
    },
    {
        "id": "3-8",
        "title": "Username and domain",
        "brief": "Write parts(email) that returns the username and the domain as a tuple, cleaned of spaces and lower case.",
        "starter": "# define parts here\n",
        "expected": "('ada.l', 'example.com')\n",
        "hidden": 'print(parts("  Ada.L@Example.COM "))\n',
        "hint": 'def parts(email):\n    email = email.strip().lower()\n    username, domain = email.split("@")\n    return username, domain',
        "concepts": ["strings", "split", "tuples", "functions"],
    },
    # add your own levels here
]
