WORLD = {"name": "Comprehensions", "title": "list and dict comprehensions"}

LEVELS = [
    {
        "id": "7-1",
        "title": "Halves",
        "brief": "Print a list with each of 2, 4, 6, 8 divided by two, using one list comprehension.",
        "starter": "",
        "expected": "[1.0, 2.0, 3.0, 4.0]\n",
        "hidden": "",
        "hint": "print([n / 2 for n in [2, 4, 6, 8]])",
        "concepts": ["comprehensions", "lists"],
    },
    {
        "id": "7-2",
        "title": "Short names",
        "brief": "Write short(names) that returns the names of 3 letters or fewer, in lower case, as a list.",
        "starter": "# define short here\n",
        "expected": "['bo', 'kim', 'zoe']\n",
        "hidden": 'print(short(["Bo", "Alexander", "Kim", "Zoe"]))\n',
        "hint": "def short(names):\n    return [name.lower() for name in names if len(name) <= 3]",
        "concepts": ["comprehensions", "if", "strings"],
    },
    {
        "id": "7-3",
        "title": "Square table",
        "brief": "Write squares(n) that returns a dict from each number 1 to n to its square, using a dict comprehension.",
        "starter": "# define squares here\n",
        "expected": "{1: 1, 2: 4, 3: 9}\n",
        "hidden": "print(squares(3))\n",
        "hint": "def squares(n):\n    return {k: k * k for k in range(1, n + 1)}",
        "concepts": ["comprehensions", "dicts", "range"],
    },
    {
        "id": "7-4",
        "title": "Evens only",
        "brief": "Print a list of just the even numbers, using a comprehension with an if.",
        "starter": "nums = [1, 2, 3, 4, 5, 6]\n",
        "expected": "[2, 4, 6]\n",
        "hidden": "",
        "hint": "print([n for n in nums if n % 2 == 0])",
        "concepts": ["comprehensions", "if", "modulo"],
    },
    {
        "id": "7-5",
        "title": "Pairs",
        "brief": "Print all (a, b) pairs with a and b from 0 to 1 where a is not b, from one comprehension with two fors.",
        "starter": "",
        "expected": "[(0, 1), (1, 0)]\n",
        "hidden": "",
        "hint": "print([(a, b) for a in range(2) for b in range(2) if a != b])",
        "concepts": ["comprehensions", "tuples", "range"],
    },
    {
        "id": "7-6",
        "title": "Any negative",
        "brief": "Write has_negative(nums) that returns True if any number is below zero, using any().",
        "starter": "# define has_negative here\n",
        "expected": "True\nFalse\n",
        "hidden": "print(has_negative([1, -2]))\nprint(has_negative([3]))\n",
        "hint": "def has_negative(nums):\n    return any(n < 0 for n in nums)",
        "concepts": ["any", "generator", "comparisons"],
    },
    {
        "id": "7-7",
        "title": "First letters",
        "brief": "Write first_letters(words) that returns the sorted list of different first letters, in lower case, using a set comprehension.",
        "starter": "# define first_letters here\n",
        "expected": "['q', 't']\n",
        "hidden": 'print(first_letters(["the", "quick", "Tall"]))\n',
        "hint": "def first_letters(words):\n    return sorted({word[0].lower() for word in words})",
        "concepts": ["set comprehension", "sorted", "strings"],
    },
    {
        "id": "7-8",
        "title": "Longest word",
        "brief": "Print the longest word, then a dict from each word longer than 3 letters to its length.",
        "starter": 'text = "the quick brown fox"\n',
        "expected": "quick\n{'quick': 5, 'brown': 5}\n",
        "hidden": "",
        "hint": "words = text.split()\nprint(max(words, key=len))\nprint({word: len(word) for word in words if len(word) > 3})",
        "concepts": ["max", "key", "dict comprehension", "split"],
    },
    # add your own levels here
]
